// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID                  int32      `json:"id"`
	Vid                 int32      `json:"vid"`
	RegDate             time.Time  `json:"reg_date"`
	QueueNo             string     `json:"queue_no"`
	Pregnant            bool       `json:"pregnant"`
	LastMenstrualPeriod *time.Time `json:"last_menstrual_period"`
	SentToID            bool       `json:"sent_to_id"`
}

type AuditLog struct {
	ID        int64     `json:"id"`
	TableName string    `json:"table_name"`
	Action    string    `json:"action"`
	RowData   []byte    `json:"row_data"`
	ByUser    *int64    `json:"by_user"`
	At        time.Time `json:"at"`
}

type BatchLocation struct {
	ID        int64      `json:"id"`
	BatchID   int64      `json:"batch_id"`
	Location  string     `json:"location"`
	Quantity  int32      `json:"quantity"`
	CreatedAt time.Time  `json:"created_at"`
	CreatedBy *int64     `json:"created_by"`
	UpdatedAt *time.Time `json:"updated_at"`
	UpdatedBy *int64     `json:"updated_by"`
}

type Dental struct {
	ID                     int32   `json:"id"`
	Vid                    int32   `json:"vid"`
	FluorideExposure       string  `json:"fluoride_exposure"`
	Diet                   string  `json:"diet"`
	BacterialExposure      string  `json:"bacterial_exposure"`
	OralSymptoms           bool    `json:"oral_symptoms"`
	DrinkOtherWater        bool    `json:"drink_other_water"`
	RiskForDentalCarries   string  `json:"risk_for_dental_carries"`
	IcopeDifficultyChewing *bool   `json:"icope_difficulty_chewing"`
	IcopePainInMouth       *bool   `json:"icope_pain_in_mouth"`
	DentalNotes            *string `json:"dental_notes"`
}

type DoctorsConsultation struct {
	ID                int32   `json:"id"`
	Vid               int32   `json:"vid"`
	Well              *bool   `json:"well"`
	Msk               *bool   `json:"msk"`
	Cvs               *bool   `json:"cvs"`
	Respi             *bool   `json:"respi"`
	Gu                *bool   `json:"gu"`
	Git               *bool   `json:"git"`
	Eye               *bool   `json:"eye"`
	Derm              *bool   `json:"derm"`
	Others            *string `json:"others"`
	ConsultationNotes *string `json:"consultation_notes"`
	Diagnosis         *string `json:"diagnosis"`
	Treatment         *string `json:"treatment"`
	ReferralNeeded    bool    `json:"referral_needed"`
	ReferralLoc       *string `json:"referral_loc"`
	Remarks           *string `json:"remarks"`
}

type DosageForm struct {
	Code  string `json:"code"`
	Label string `json:"label"`
}

type Drug struct {
	ID                  int64          `json:"id"`
	GenericName         string         `json:"generic_name"`
	BrandName           *string        `json:"brand_name"`
	DrugCode            *int32         `json:"drug_code"`
	DosageFormCode      string         `json:"dosage_form_code"`
	RouteCode           string         `json:"route_code"`
	StrengthNum         pgtype.Numeric `json:"strength_num"`
	StrengthUnitNum     *string        `json:"strength_unit_num"`
	StrengthDen         pgtype.Numeric `json:"strength_den"`
	StrengthUnitDen     *string        `json:"strength_unit_den"`
	DispenseUnit        string         `json:"dispense_unit"`
	PieceContentAmount  pgtype.Numeric `json:"piece_content_amount"`
	PieceContentUnit    *string        `json:"piece_content_unit"`
	IsFractionalAllowed *bool          `json:"is_fractional_allowed"`
	DisplayAsPercentage *bool          `json:"display_as_percentage"`
	IsActive            bool           `json:"is_active"`
	Barcode             *string        `json:"barcode"`
	Notes               *string        `json:"notes"`
	CreatedAt           time.Time      `json:"created_at"`
	CreatedBy           *int64         `json:"created_by"`
	UpdatedAt           *time.Time     `json:"updated_at"`
	UpdatedBy           *int64         `json:"updated_by"`
}

type DrugBatch struct {
	ID          int64      `json:"id"`
	DrugID      int64      `json:"drug_id"`
	BatchNumber string     `json:"batch_number"`
	ExpiryDate  *time.Time `json:"expiry_date"`
	Supplier    *string    `json:"supplier"`
	Quantity    int32      `json:"quantity"`
	CreatedAt   time.Time  `json:"created_at"`
	CreatedBy   *int64     `json:"created_by"`
	UpdatedAt   *time.Time `json:"updated_at"`
	UpdatedBy   *int64     `json:"updated_by"`
}

type FallRisk struct {
	ID                       int32 `json:"id"`
	Vid                      int32 `json:"vid"`
	SideToSideBalance        int32 `json:"side_to_side_balance"`
	SemiTandemBalance        int32 `json:"semi_tandem_balance"`
	TandemBalance            int32 `json:"tandem_balance"`
	GaitSpeedTest            int32 `json:"gait_speed_test"`
	ChairStandTest           int32 `json:"chair_stand_test"`
	FallRiskScore            int32 `json:"fall_risk_score"`
	IcopeCompleteChairStands *bool `json:"icope_complete_chair_stands"`
	IcopeChairStandsTime     *bool `json:"icope_chair_stands_time"`
}

type FrequencyCode struct {
	Code                 string         `json:"code"`
	Label                string         `json:"label"`
	ScheduleKind         string         `json:"schedule_kind"`
	EveryN               int32          `json:"every_n"`
	FrequencyPerSchedule pgtype.Numeric `json:"frequency_per_schedule"`
}

type HeightAndWeight struct {
	ID                        int32          `json:"id"`
	Vid                       int32          `json:"vid"`
	Height                    pgtype.Numeric `json:"height"`
	Weight                    pgtype.Numeric `json:"weight"`
	Bmi                       pgtype.Numeric `json:"bmi"`
	BmiAnalysis               string         `json:"bmi_analysis"`
	PaedsHeight               pgtype.Numeric `json:"paeds_height"`
	PaedsWeight               pgtype.Numeric `json:"paeds_weight"`
	IcopeLostWeightPastMonths *bool          `json:"icope_lost_weight_past_months"`
	IcopeNoDesireToEat        *bool          `json:"icope_no_desire_to_eat"`
}

type PastMedicalHistory struct {
	ID                         int32   `json:"id"`
	Vid                        int32   `json:"vid"`
	Cough                      *bool   `json:"cough"`
	Fever                      *bool   `json:"fever"`
	BlockedNose                *bool   `json:"blocked_nose"`
	SoreThroat                 *bool   `json:"sore_throat"`
	NightSweats                *bool   `json:"night_sweats"`
	UnintentionalWeightLoss    *bool   `json:"unintentional_weight_loss"`
	Tuberculosis               *bool   `json:"tuberculosis"`
	TuberculosisHasBeenTreated *bool   `json:"tuberculosis_has_been_treated"`
	Diabetes                   *bool   `json:"diabetes"`
	Hypertension               *bool   `json:"hypertension"`
	Hyperlipidemia             *bool   `json:"hyperlipidemia"`
	ChronicJointPains          *bool   `json:"chronic_joint_pains"`
	ChronicMuscleAches         *bool   `json:"chronic_muscle_aches"`
	SexuallyTransmittedDisease *bool   `json:"sexually_transmitted_disease"`
	SpecifiedStds              *string `json:"specified_stds"`
	Others                     *string `json:"others"`
}

type PatientDetail struct {
	ID            int32     `json:"id"`
	Name          string    `json:"name"`
	FamilyGroup   string    `json:"family_group"`
	KhmerName     string    `json:"khmer_name"`
	Dob           time.Time `json:"dob"`
	Gender        string    `json:"gender"`
	Village       string    `json:"village"`
	ContactNo     *string   `json:"contact_no"`
	DrugAllergies *string   `json:"drug_allergies"`
}

type Physiotherapy struct {
	ID                   int32   `json:"id"`
	Vid                  int32   `json:"vid"`
	SubjectiveAssessment *string `json:"subjective_assessment"`
	PainScale            *int32  `json:"pain_scale"`
	ObjectiveAssessment  *string `json:"objective_assessment"`
	Intervention         *string `json:"intervention"`
	Evaluation           *string `json:"evaluation"`
}

type Prescription struct {
	ID          int64      `json:"id"`
	PatientID   int32      `json:"patient_id"`
	Vid         int32      `json:"vid"`
	Notes       *string    `json:"notes"`
	IsDispensed bool       `json:"is_dispensed"`
	DispensedBy *int64     `json:"dispensed_by"`
	DispensedAt *time.Time `json:"dispensed_at"`
	CreatedAt   time.Time  `json:"created_at"`
	CreatedBy   *int64     `json:"created_by"`
	UpdatedAt   *time.Time `json:"updated_at"`
	UpdatedBy   *int64     `json:"updated_by"`
}

type PrescriptionBatchItem struct {
	ID              int64      `json:"id"`
	LineID          int64      `json:"line_id"`
	BatchLocationID int64      `json:"batch_location_id"`
	Quantity        int32      `json:"quantity"`
	CreatedAt       time.Time  `json:"created_at"`
	CreatedBy       *int64     `json:"created_by"`
	UpdatedAt       *time.Time `json:"updated_at"`
	UpdatedBy       *int64     `json:"updated_by"`
}

type PrescriptionLine struct {
	ID              int64      `json:"id"`
	PrescriptionID  int64      `json:"prescription_id"`
	DrugID          int64      `json:"drug_id"`
	Remarks         *string    `json:"remarks"`
	Prn             bool       `json:"prn"`
	DoseAmount      float64    `json:"dose_amount"`
	DoseUnit        string     `json:"dose_unit"`
	FrequencyCode   string     `json:"frequency_code"`
	Duration        float64    `json:"duration"`
	DurationUnit    string     `json:"duration_unit"`
	TotalToDispense int32      `json:"total_to_dispense"`
	IsPacked        bool       `json:"is_packed"`
	PackedBy        *int64     `json:"packed_by"`
	PackedAt        *time.Time `json:"packed_at"`
	CreatedAt       time.Time  `json:"created_at"`
	CreatedBy       *int64     `json:"created_by"`
	UpdatedAt       *time.Time `json:"updated_at"`
	UpdatedBy       *int64     `json:"updated_by"`
}

type Route struct {
	Code  string `json:"code"`
	Label string `json:"label"`
}

type ScheduleKind struct {
	Code string `json:"code"`
}

type SocialHistory struct {
	ID                    int32   `json:"id"`
	Vid                   int32   `json:"vid"`
	PastSmokingHistory    bool    `json:"past_smoking_history"`
	NoOfYears             *int32  `json:"no_of_years"`
	CurrentSmokingHistory bool    `json:"current_smoking_history"`
	CigarettesPerDay      *int32  `json:"cigarettes_per_day"`
	AlcoholHistory        bool    `json:"alcohol_history"`
	HowRegular            *string `json:"how_regular"`
}

type Unit struct {
	Code     string `json:"code"`
	IsMass   bool   `json:"is_mass"`
	IsVolume bool   `json:"is_volume"`
	IsPiece  bool   `json:"is_piece"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Name      *string   `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type VisualAcuity struct {
	ID                          int32   `json:"id"`
	Vid                         int32   `json:"vid"`
	LEyeVision                  int32   `json:"l_eye_vision"`
	REyeVision                  int32   `json:"r_eye_vision"`
	AdditionalIntervention      *string `json:"additional_intervention"`
	SentToOpto                  bool    `json:"sent_to_opto"`
	ReferredForGlasses          bool    `json:"referred_for_glasses"`
	IcopeEyeProblem             *bool   `json:"icope_eye_problem"`
	IcopeTreatedForDiabetesOrBp *bool   `json:"icope_treated_for_diabetes_or_bp"`
}

type VitalStatistic struct {
	ID                    int32          `json:"id"`
	Vid                   int32          `json:"vid"`
	Temperature           pgtype.Numeric `json:"temperature"`
	Spo2                  pgtype.Numeric `json:"spo2"`
	SystolicBp1           pgtype.Numeric `json:"systolic_bp1"`
	DiastolicBp1          pgtype.Numeric `json:"diastolic_bp1"`
	SystolicBp2           pgtype.Numeric `json:"systolic_bp2"`
	DiastolicBp2          pgtype.Numeric `json:"diastolic_bp2"`
	AvgSystolicBp         pgtype.Numeric `json:"avg_systolic_bp"`
	AvgDiastolicBp        pgtype.Numeric `json:"avg_diastolic_bp"`
	Hr1                   pgtype.Numeric `json:"hr1"`
	Hr2                   pgtype.Numeric `json:"hr2"`
	AvgHr                 pgtype.Numeric `json:"avg_hr"`
	RandBloodGlucoseMmolL pgtype.Numeric `json:"rand_blood_glucose_mmol_l"`
	IcopeHighBp           *bool          `json:"icope_high_bp"`
}
