// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: patient.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkPatientExists = `-- name: CheckPatientExists :one
SELECT id
FROM patient_details
WHERE id = $1
LIMIT 1
`

func (q *Queries) CheckPatientExists(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, checkPatientExists, id)
	err := row.Scan(&id)
	return id, err
}

const checkPatientVisitExists = `-- name: CheckPatientVisitExists :one
SELECT id, vid
FROM admin
WHERE id = $1
  AND vid = $2
LIMIT 1
`

type CheckPatientVisitExistsParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

type CheckPatientVisitExistsRow struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

func (q *Queries) CheckPatientVisitExists(ctx context.Context, arg CheckPatientVisitExistsParams) (CheckPatientVisitExistsRow, error) {
	row := q.db.QueryRow(ctx, checkPatientVisitExists, arg.ID, arg.Vid)
	var i CheckPatientVisitExistsRow
	err := row.Scan(&i.ID, &i.Vid)
	return i, err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM admin
WHERE id = $1
  AND vid = $2
`

type DeleteAdminParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

func (q *Queries) DeleteAdmin(ctx context.Context, arg DeleteAdminParams) error {
	_, err := q.db.Exec(ctx, deleteAdmin, arg.ID, arg.Vid)
	return err
}

const deleteDental = `-- name: DeleteDental :exec
DELETE FROM dental
WHERE id = $1
  AND vid = $2
`

type DeleteDentalParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

func (q *Queries) DeleteDental(ctx context.Context, arg DeleteDentalParams) error {
	_, err := q.db.Exec(ctx, deleteDental, arg.ID, arg.Vid)
	return err
}

const deleteDoctorsConsultation = `-- name: DeleteDoctorsConsultation :exec
DELETE FROM doctors_consultation
WHERE id = $1
  AND vid = $2
`

type DeleteDoctorsConsultationParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

func (q *Queries) DeleteDoctorsConsultation(ctx context.Context, arg DeleteDoctorsConsultationParams) error {
	_, err := q.db.Exec(ctx, deleteDoctorsConsultation, arg.ID, arg.Vid)
	return err
}

const deleteFallRisk = `-- name: DeleteFallRisk :exec
DELETE FROM fall_risk
WHERE id = $1
  AND vid = $2
`

type DeleteFallRiskParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

func (q *Queries) DeleteFallRisk(ctx context.Context, arg DeleteFallRiskParams) error {
	_, err := q.db.Exec(ctx, deleteFallRisk, arg.ID, arg.Vid)
	return err
}

const deleteHeightAndWeight = `-- name: DeleteHeightAndWeight :exec
DELETE FROM height_and_weight
WHERE id = $1
  AND vid = $2
`

type DeleteHeightAndWeightParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

func (q *Queries) DeleteHeightAndWeight(ctx context.Context, arg DeleteHeightAndWeightParams) error {
	_, err := q.db.Exec(ctx, deleteHeightAndWeight, arg.ID, arg.Vid)
	return err
}

const deletePastMedicalHistory = `-- name: DeletePastMedicalHistory :exec
DELETE FROM past_medical_history
WHERE id = $1
  AND vid = $2
`

type DeletePastMedicalHistoryParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

func (q *Queries) DeletePastMedicalHistory(ctx context.Context, arg DeletePastMedicalHistoryParams) error {
	_, err := q.db.Exec(ctx, deletePastMedicalHistory, arg.ID, arg.Vid)
	return err
}

const deletePhysiotherapy = `-- name: DeletePhysiotherapy :exec
DELETE FROM physiotherapy
WHERE id = $1
  AND vid = $2
`

type DeletePhysiotherapyParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

func (q *Queries) DeletePhysiotherapy(ctx context.Context, arg DeletePhysiotherapyParams) error {
	_, err := q.db.Exec(ctx, deletePhysiotherapy, arg.ID, arg.Vid)
	return err
}

const deleteSocialHistory = `-- name: DeleteSocialHistory :exec
DELETE FROM social_history
WHERE id = $1
  AND vid = $2
`

type DeleteSocialHistoryParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

func (q *Queries) DeleteSocialHistory(ctx context.Context, arg DeleteSocialHistoryParams) error {
	_, err := q.db.Exec(ctx, deleteSocialHistory, arg.ID, arg.Vid)
	return err
}

const deleteVisualAcuity = `-- name: DeleteVisualAcuity :exec
DELETE FROM visual_acuity
WHERE id = $1
  AND vid = $2
`

type DeleteVisualAcuityParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

func (q *Queries) DeleteVisualAcuity(ctx context.Context, arg DeleteVisualAcuityParams) error {
	_, err := q.db.Exec(ctx, deleteVisualAcuity, arg.ID, arg.Vid)
	return err
}

const deleteVitalStatistics = `-- name: DeleteVitalStatistics :exec
DELETE FROM vital_statistics
WHERE id = $1
  AND vid = $2
`

type DeleteVitalStatisticsParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

func (q *Queries) DeleteVitalStatistics(ctx context.Context, arg DeleteVitalStatisticsParams) error {
	_, err := q.db.Exec(ctx, deleteVitalStatistics, arg.ID, arg.Vid)
	return err
}

const getAdmin = `-- name: GetAdmin :one

SELECT id,
       vid,
       reg_date,
       queue_no,
       pregnant,
       last_menstrual_period,
       sent_to_id
FROM admin
WHERE id = $1
  AND vid = $2
`

type GetAdminParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

// Admin ----------------------------------------------------------------------
func (q *Queries) GetAdmin(ctx context.Context, arg GetAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdmin, arg.ID, arg.Vid)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Vid,
		&i.RegDate,
		&i.QueueNo,
		&i.Pregnant,
		&i.LastMenstrualPeriod,
		&i.SentToID,
	)
	return i, err
}

const getDental = `-- name: GetDental :one

SELECT id,
       vid,
       fluoride_exposure,
       diet,
       bacterial_exposure,
       oral_symptoms,
       drink_other_water,
       risk_for_dental_carries,
       icope_difficulty_chewing,
       icope_pain_in_mouth,
       dental_notes
FROM dental
WHERE id = $1
  AND vid = $2
`

type GetDentalParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

// Dental ---------------------------------------------------------------------
func (q *Queries) GetDental(ctx context.Context, arg GetDentalParams) (Dental, error) {
	row := q.db.QueryRow(ctx, getDental, arg.ID, arg.Vid)
	var i Dental
	err := row.Scan(
		&i.ID,
		&i.Vid,
		&i.FluorideExposure,
		&i.Diet,
		&i.BacterialExposure,
		&i.OralSymptoms,
		&i.DrinkOtherWater,
		&i.RiskForDentalCarries,
		&i.IcopeDifficultyChewing,
		&i.IcopePainInMouth,
		&i.DentalNotes,
	)
	return i, err
}

const getDoctorsConsultation = `-- name: GetDoctorsConsultation :one

SELECT id,
       vid,
       well,
       msk,
       cvs,
       respi,
       gu,
       git,
       eye,
       derm,
       others,
       consultation_notes,
       diagnosis,
       treatment,
       referral_needed,
       referral_loc,
       remarks
FROM doctors_consultation
WHERE id = $1
  AND vid = $2
`

type GetDoctorsConsultationParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

// Doctors Consultation -------------------------------------------------------
func (q *Queries) GetDoctorsConsultation(ctx context.Context, arg GetDoctorsConsultationParams) (DoctorsConsultation, error) {
	row := q.db.QueryRow(ctx, getDoctorsConsultation, arg.ID, arg.Vid)
	var i DoctorsConsultation
	err := row.Scan(
		&i.ID,
		&i.Vid,
		&i.Well,
		&i.Msk,
		&i.Cvs,
		&i.Respi,
		&i.Gu,
		&i.Git,
		&i.Eye,
		&i.Derm,
		&i.Others,
		&i.ConsultationNotes,
		&i.Diagnosis,
		&i.Treatment,
		&i.ReferralNeeded,
		&i.ReferralLoc,
		&i.Remarks,
	)
	return i, err
}

const getFallRisk = `-- name: GetFallRisk :one

SELECT id,
       vid,
       side_to_side_balance,
       semi_tandem_balance,
       tandem_balance,
       gait_speed_test,
       chair_stand_test,
       fall_risk_score,
       icope_complete_chair_stands,
       icope_chair_stands_time
FROM fall_risk
WHERE id = $1
  AND vid = $2
`

type GetFallRiskParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

// Fall Risk ------------------------------------------------------------------
func (q *Queries) GetFallRisk(ctx context.Context, arg GetFallRiskParams) (FallRisk, error) {
	row := q.db.QueryRow(ctx, getFallRisk, arg.ID, arg.Vid)
	var i FallRisk
	err := row.Scan(
		&i.ID,
		&i.Vid,
		&i.SideToSideBalance,
		&i.SemiTandemBalance,
		&i.TandemBalance,
		&i.GaitSpeedTest,
		&i.ChairStandTest,
		&i.FallRiskScore,
		&i.IcopeCompleteChairStands,
		&i.IcopeChairStandsTime,
	)
	return i, err
}

const getHeightAndWeight = `-- name: GetHeightAndWeight :one

SELECT id,
       vid,
       height,
       weight,
       bmi,
       bmi_analysis,
       paeds_height,
       paeds_weight,
       icope_lost_weight_past_months,
       icope_no_desire_to_eat
FROM height_and_weight
WHERE id = $1
  AND vid = $2
`

type GetHeightAndWeightParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

// Height and Weight ----------------------------------------------------------
func (q *Queries) GetHeightAndWeight(ctx context.Context, arg GetHeightAndWeightParams) (HeightAndWeight, error) {
	row := q.db.QueryRow(ctx, getHeightAndWeight, arg.ID, arg.Vid)
	var i HeightAndWeight
	err := row.Scan(
		&i.ID,
		&i.Vid,
		&i.Height,
		&i.Weight,
		&i.Bmi,
		&i.BmiAnalysis,
		&i.PaedsHeight,
		&i.PaedsWeight,
		&i.IcopeLostWeightPastMonths,
		&i.IcopeNoDesireToEat,
	)
	return i, err
}

const getLatestAdmin = `-- name: GetLatestAdmin :one
SELECT id,
       vid,
       reg_date,
       queue_no
FROM admin
WHERE id = $1
ORDER BY reg_date DESC, vid DESC
LIMIT 1
`

type GetLatestAdminRow struct {
	ID      int32     `json:"id"`
	Vid     int32     `json:"vid"`
	RegDate time.Time `json:"reg_date"`
	QueueNo string    `json:"queue_no"`
}

func (q *Queries) GetLatestAdmin(ctx context.Context, id int32) (GetLatestAdminRow, error) {
	row := q.db.QueryRow(ctx, getLatestAdmin, id)
	var i GetLatestAdminRow
	err := row.Scan(
		&i.ID,
		&i.Vid,
		&i.RegDate,
		&i.QueueNo,
	)
	return i, err
}

const getPastMedicalHistory = `-- name: GetPastMedicalHistory :one

SELECT id,
       vid,
       cough,
       fever,
       blocked_nose,
       sore_throat,
       night_sweats,
       unintentional_weight_loss,
       tuberculosis,
       tuberculosis_has_been_treated,
       diabetes,
       hypertension,
       hyperlipidemia,
       chronic_joint_pains,
       chronic_muscle_aches,
       sexually_transmitted_disease,
       specified_stds,
       others
FROM past_medical_history
WHERE id = $1
  AND vid = $2
`

type GetPastMedicalHistoryParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

// Past Medical History -------------------------------------------------------
func (q *Queries) GetPastMedicalHistory(ctx context.Context, arg GetPastMedicalHistoryParams) (PastMedicalHistory, error) {
	row := q.db.QueryRow(ctx, getPastMedicalHistory, arg.ID, arg.Vid)
	var i PastMedicalHistory
	err := row.Scan(
		&i.ID,
		&i.Vid,
		&i.Cough,
		&i.Fever,
		&i.BlockedNose,
		&i.SoreThroat,
		&i.NightSweats,
		&i.UnintentionalWeightLoss,
		&i.Tuberculosis,
		&i.TuberculosisHasBeenTreated,
		&i.Diabetes,
		&i.Hypertension,
		&i.Hyperlipidemia,
		&i.ChronicJointPains,
		&i.ChronicMuscleAches,
		&i.SexuallyTransmittedDisease,
		&i.SpecifiedStds,
		&i.Others,
	)
	return i, err
}

const getPatient = `-- name: GetPatient :one

SELECT id,
       name,
       family_group,
       khmer_name,
       dob,
       gender,
       village,
       contact_no,
       drug_allergies
FROM patient_details
WHERE id = $1
`

// Patient --------------------------------------------------------------------
func (q *Queries) GetPatient(ctx context.Context, id int32) (PatientDetail, error) {
	row := q.db.QueryRow(ctx, getPatient, id)
	var i PatientDetail
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FamilyGroup,
		&i.KhmerName,
		&i.Dob,
		&i.Gender,
		&i.Village,
		&i.ContactNo,
		&i.DrugAllergies,
	)
	return i, err
}

const getPatientVisitMetaByDate = `-- name: GetPatientVisitMetaByDate :many
SELECT DISTINCT ON (a.id)
  a.id,
  a.vid,
  p.family_group,
  a.reg_date,
  a.queue_no,
  p.name,
  p.khmer_name,
  p.gender,
  p.village,
  p.contact_no,
  p.drug_allergies,
  a.sent_to_id,
  dc.referral_needed,
  EXISTS (
    SELECT 1
    FROM prescriptions pr
    JOIN prescription_lines pl ON pl.prescription_id = pr.id
    WHERE pr.patient_id = a.id
      AND pr.vid = a.vid
  ) AS has_prescription_with_drug,
  CASE
    WHEN EXISTS (
      SELECT 1
      FROM prescriptions pr
      JOIN prescription_lines pl ON pl.prescription_id = pr.id
      WHERE pr.patient_id = a.id
        AND pr.vid = a.vid
    ) THEN NOT EXISTS (
      SELECT 1
      FROM prescriptions pr
      JOIN prescription_lines pl ON pl.prescription_id = pr.id
      WHERE pr.patient_id = a.id
        AND pr.vid = a.vid
        AND (pl.is_packed IS NOT TRUE)
    )
    ELSE FALSE
  END AS all_prescription_drugs_packed,
  EXISTS (
    SELECT 1
    FROM prescriptions pr
    WHERE pr.patient_id = a.id
      AND pr.vid = a.vid
      AND pr.is_dispensed = TRUE
  ) AS prescription_dispensed
FROM admin a
JOIN patient_details p ON p.id = a.id
LEFT JOIN doctors_consultation dc
  ON a.id = dc.id AND a.vid = dc.vid
WHERE a.reg_date = $1
ORDER BY a.id, a.vid DESC
`

type GetPatientVisitMetaByDateRow struct {
	ID                         int32     `json:"id"`
	Vid                        int32     `json:"vid"`
	FamilyGroup                string    `json:"family_group"`
	RegDate                    time.Time `json:"reg_date"`
	QueueNo                    string    `json:"queue_no"`
	Name                       string    `json:"name"`
	KhmerName                  string    `json:"khmer_name"`
	Gender                     string    `json:"gender"`
	Village                    string    `json:"village"`
	ContactNo                  string    `json:"contact_no"`
	DrugAllergies              *string   `json:"drug_allergies"`
	SentToID                   bool      `json:"sent_to_id"`
	ReferralNeeded             *bool     `json:"referral_needed"`
	HasPrescriptionWithDrug    bool      `json:"has_prescription_with_drug"`
	AllPrescriptionDrugsPacked bool      `json:"all_prescription_drugs_packed"`
	PrescriptionDispensed      bool      `json:"prescription_dispensed"`
}

func (q *Queries) GetPatientVisitMetaByDate(ctx context.Context, regDate time.Time) ([]GetPatientVisitMetaByDateRow, error) {
	rows, err := q.db.Query(ctx, getPatientVisitMetaByDate, regDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPatientVisitMetaByDateRow
	for rows.Next() {
		var i GetPatientVisitMetaByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.Vid,
			&i.FamilyGroup,
			&i.RegDate,
			&i.QueueNo,
			&i.Name,
			&i.KhmerName,
			&i.Gender,
			&i.Village,
			&i.ContactNo,
			&i.DrugAllergies,
			&i.SentToID,
			&i.ReferralNeeded,
			&i.HasPrescriptionWithDrug,
			&i.AllPrescriptionDrugsPacked,
			&i.PrescriptionDispensed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPatientVisitMetaLatest = `-- name: GetPatientVisitMetaLatest :many

WITH LatestDates AS (
  SELECT id, MAX(reg_date) AS latest_reg_date
  FROM admin
  GROUP BY id
)
SELECT DISTINCT ON (a.id)
  a.id,
  a.vid,
  p.family_group,
  a.reg_date,
  a.queue_no,
  p.name,
  p.khmer_name,
  p.gender,
  p.village,
  p.contact_no,
  p.drug_allergies,
  a.sent_to_id,
  dc.referral_needed,
  EXISTS (
    SELECT 1
    FROM prescriptions pr
    JOIN prescription_lines pl ON pl.prescription_id = pr.id
    WHERE pr.patient_id = a.id
      AND pr.vid = a.vid
  ) AS has_prescription_with_drug,
  CASE
    WHEN EXISTS (
      SELECT 1
      FROM prescriptions pr
      JOIN prescription_lines pl ON pl.prescription_id = pr.id
      WHERE pr.patient_id = a.id
        AND pr.vid = a.vid
    ) THEN NOT EXISTS (
      SELECT 1
      FROM prescriptions pr
      JOIN prescription_lines pl ON pl.prescription_id = pr.id
      WHERE pr.patient_id = a.id
        AND pr.vid = a.vid
        AND (pl.is_packed IS NOT TRUE)
    )
    ELSE FALSE
  END AS all_prescription_drugs_packed,
  EXISTS (
    SELECT 1
    FROM prescriptions pr
    WHERE pr.patient_id = a.id
      AND pr.vid = a.vid
      AND pr.is_dispensed = TRUE
  ) AS prescription_dispensed
FROM admin a
JOIN patient_details p ON p.id = a.id
LEFT JOIN doctors_consultation dc
  ON a.id = dc.id AND a.vid = dc.vid
INNER JOIN LatestDates ld
  ON a.id = ld.id AND a.reg_date = ld.latest_reg_date
ORDER BY a.id, a.vid DESC
`

type GetPatientVisitMetaLatestRow struct {
	ID                         int32     `json:"id"`
	Vid                        int32     `json:"vid"`
	FamilyGroup                string    `json:"family_group"`
	RegDate                    time.Time `json:"reg_date"`
	QueueNo                    string    `json:"queue_no"`
	Name                       string    `json:"name"`
	KhmerName                  string    `json:"khmer_name"`
	Gender                     string    `json:"gender"`
	Village                    string    `json:"village"`
	ContactNo                  string    `json:"contact_no"`
	DrugAllergies              *string   `json:"drug_allergies"`
	SentToID                   bool      `json:"sent_to_id"`
	ReferralNeeded             *bool     `json:"referral_needed"`
	HasPrescriptionWithDrug    bool      `json:"has_prescription_with_drug"`
	AllPrescriptionDrugsPacked bool      `json:"all_prescription_drugs_packed"`
	PrescriptionDispensed      bool      `json:"prescription_dispensed"`
}

// Patient Metadata -----------------------------------------------------------
func (q *Queries) GetPatientVisitMetaLatest(ctx context.Context) ([]GetPatientVisitMetaLatestRow, error) {
	rows, err := q.db.Query(ctx, getPatientVisitMetaLatest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPatientVisitMetaLatestRow
	for rows.Next() {
		var i GetPatientVisitMetaLatestRow
		if err := rows.Scan(
			&i.ID,
			&i.Vid,
			&i.FamilyGroup,
			&i.RegDate,
			&i.QueueNo,
			&i.Name,
			&i.KhmerName,
			&i.Gender,
			&i.Village,
			&i.ContactNo,
			&i.DrugAllergies,
			&i.SentToID,
			&i.ReferralNeeded,
			&i.HasPrescriptionWithDrug,
			&i.AllPrescriptionDrugsPacked,
			&i.PrescriptionDispensed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhysiotherapy = `-- name: GetPhysiotherapy :one

SELECT id,
       vid,
       subjective_assessment,
       pain_scale,
       objective_assessment,
       intervention,
       evaluation
FROM physiotherapy
WHERE id = $1
  AND vid = $2
`

type GetPhysiotherapyParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

// Physiotherapy --------------------------------------------------------------
func (q *Queries) GetPhysiotherapy(ctx context.Context, arg GetPhysiotherapyParams) (Physiotherapy, error) {
	row := q.db.QueryRow(ctx, getPhysiotherapy, arg.ID, arg.Vid)
	var i Physiotherapy
	err := row.Scan(
		&i.ID,
		&i.Vid,
		&i.SubjectiveAssessment,
		&i.PainScale,
		&i.ObjectiveAssessment,
		&i.Intervention,
		&i.Evaluation,
	)
	return i, err
}

const getSocialHistory = `-- name: GetSocialHistory :one

SELECT id,
       vid,
       past_smoking_history,
       no_of_years,
       current_smoking_history,
       cigarettes_per_day,
       alcohol_history,
       how_regular
FROM social_history
WHERE id = $1
  AND vid = $2
`

type GetSocialHistoryParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

// Social History -------------------------------------------------------------
func (q *Queries) GetSocialHistory(ctx context.Context, arg GetSocialHistoryParams) (SocialHistory, error) {
	row := q.db.QueryRow(ctx, getSocialHistory, arg.ID, arg.Vid)
	var i SocialHistory
	err := row.Scan(
		&i.ID,
		&i.Vid,
		&i.PastSmokingHistory,
		&i.NoOfYears,
		&i.CurrentSmokingHistory,
		&i.CigarettesPerDay,
		&i.AlcoholHistory,
		&i.HowRegular,
	)
	return i, err
}

const getVisualAcuity = `-- name: GetVisualAcuity :one

SELECT id,
       vid,
       l_eye_vision,
       r_eye_vision,
       additional_intervention,
       sent_to_opto,
       referred_for_glasses,
       icope_eye_problem,
       icope_treated_for_diabetes_or_bp
FROM visual_acuity
WHERE id = $1
  AND vid = $2
`

type GetVisualAcuityParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

// Visual Acuity --------------------------------------------------------------
func (q *Queries) GetVisualAcuity(ctx context.Context, arg GetVisualAcuityParams) (VisualAcuity, error) {
	row := q.db.QueryRow(ctx, getVisualAcuity, arg.ID, arg.Vid)
	var i VisualAcuity
	err := row.Scan(
		&i.ID,
		&i.Vid,
		&i.LEyeVision,
		&i.REyeVision,
		&i.AdditionalIntervention,
		&i.SentToOpto,
		&i.ReferredForGlasses,
		&i.IcopeEyeProblem,
		&i.IcopeTreatedForDiabetesOrBp,
	)
	return i, err
}

const getVitalStatistics = `-- name: GetVitalStatistics :one

SELECT id,
       vid,
       temperature,
       spo2,
       systolic_bp1,
       diastolic_bp1,
       systolic_bp2,
       diastolic_bp2,
       avg_systolic_bp,
       avg_diastolic_bp,
       hr1,
       hr2,
       avg_hr,
       rand_blood_glucose_mmol_l,
       icope_high_bp
FROM vital_statistics
WHERE id = $1
  AND vid = $2
`

type GetVitalStatisticsParams struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

// Vital Statistics -----------------------------------------------------------
func (q *Queries) GetVitalStatistics(ctx context.Context, arg GetVitalStatisticsParams) (VitalStatistic, error) {
	row := q.db.QueryRow(ctx, getVitalStatistics, arg.ID, arg.Vid)
	var i VitalStatistic
	err := row.Scan(
		&i.ID,
		&i.Vid,
		&i.Temperature,
		&i.Spo2,
		&i.SystolicBp1,
		&i.DiastolicBp1,
		&i.SystolicBp2,
		&i.DiastolicBp2,
		&i.AvgSystolicBp,
		&i.AvgDiastolicBp,
		&i.Hr1,
		&i.Hr2,
		&i.AvgHr,
		&i.RandBloodGlucoseMmolL,
		&i.IcopeHighBp,
	)
	return i, err
}

const insertPatient = `-- name: InsertPatient :one
INSERT INTO patient_details (
  name,
  family_group,
  khmer_name,
  dob,
  gender,
  village,
  contact_no,
  drug_allergies
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id
`

type InsertPatientParams struct {
	Name          string    `json:"name"`
	FamilyGroup   string    `json:"family_group"`
	KhmerName     string    `json:"khmer_name"`
	Dob           time.Time `json:"dob"`
	Gender        string    `json:"gender"`
	Village       string    `json:"village"`
	ContactNo     string    `json:"contact_no"`
	DrugAllergies *string   `json:"drug_allergies"`
}

func (q *Queries) InsertPatient(ctx context.Context, arg InsertPatientParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertPatient,
		arg.Name,
		arg.FamilyGroup,
		arg.KhmerName,
		arg.Dob,
		arg.Gender,
		arg.Village,
		arg.ContactNo,
		arg.DrugAllergies,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertPatientVisit = `-- name: InsertPatientVisit :one
INSERT INTO admin (
  id,
  reg_date,
  queue_no,
  pregnant,
  last_menstrual_period,
  sent_to_id
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, vid
`

type InsertPatientVisitParams struct {
	ID                  int32      `json:"id"`
	RegDate             time.Time  `json:"reg_date"`
	QueueNo             string     `json:"queue_no"`
	Pregnant            bool       `json:"pregnant"`
	LastMenstrualPeriod *time.Time `json:"last_menstrual_period"`
	SentToID            bool       `json:"sent_to_id"`
}

type InsertPatientVisitRow struct {
	ID  int32 `json:"id"`
	Vid int32 `json:"vid"`
}

func (q *Queries) InsertPatientVisit(ctx context.Context, arg InsertPatientVisitParams) (InsertPatientVisitRow, error) {
	row := q.db.QueryRow(ctx, insertPatientVisit,
		arg.ID,
		arg.RegDate,
		arg.QueueNo,
		arg.Pregnant,
		arg.LastMenstrualPeriod,
		arg.SentToID,
	)
	var i InsertPatientVisitRow
	err := row.Scan(&i.ID, &i.Vid)
	return i, err
}

const listAdminVisits = `-- name: ListAdminVisits :many
SELECT vid, reg_date
FROM admin
WHERE id = $1
ORDER BY vid
`

type ListAdminVisitsRow struct {
	Vid     int32     `json:"vid"`
	RegDate time.Time `json:"reg_date"`
}

func (q *Queries) ListAdminVisits(ctx context.Context, id int32) ([]ListAdminVisitsRow, error) {
	rows, err := q.db.Query(ctx, listAdminVisits, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminVisitsRow
	for rows.Next() {
		var i ListAdminVisitsRow
		if err := rows.Scan(&i.Vid, &i.RegDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdmin = `-- name: UpdateAdmin :exec
UPDATE admin
SET reg_date              = $1,
    queue_no              = $2,
    pregnant              = $3,
    last_menstrual_period = $4,
    sent_to_id            = $5
WHERE id = $6
  AND vid = $7
`

type UpdateAdminParams struct {
	RegDate             time.Time  `json:"reg_date"`
	QueueNo             string     `json:"queue_no"`
	Pregnant            bool       `json:"pregnant"`
	LastMenstrualPeriod *time.Time `json:"last_menstrual_period"`
	SentToID            bool       `json:"sent_to_id"`
	ID                  int32      `json:"id"`
	Vid                 int32      `json:"vid"`
}

func (q *Queries) UpdateAdmin(ctx context.Context, arg UpdateAdminParams) error {
	_, err := q.db.Exec(ctx, updateAdmin,
		arg.RegDate,
		arg.QueueNo,
		arg.Pregnant,
		arg.LastMenstrualPeriod,
		arg.SentToID,
		arg.ID,
		arg.Vid,
	)
	return err
}

const updatePatient = `-- name: UpdatePatient :exec
UPDATE patient_details
SET name           = $1,
    family_group   = $2,
    khmer_name     = $3,
    dob            = $4,
    gender         = $5,
    village        = $6,
    contact_no     = $7,
    drug_allergies = $8
WHERE id = $9
`

type UpdatePatientParams struct {
	Name          string    `json:"name"`
	FamilyGroup   string    `json:"family_group"`
	KhmerName     string    `json:"khmer_name"`
	Dob           time.Time `json:"dob"`
	Gender        string    `json:"gender"`
	Village       string    `json:"village"`
	ContactNo     string    `json:"contact_no"`
	DrugAllergies *string   `json:"drug_allergies"`
	ID            int32     `json:"id"`
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) error {
	_, err := q.db.Exec(ctx, updatePatient,
		arg.Name,
		arg.FamilyGroup,
		arg.KhmerName,
		arg.Dob,
		arg.Gender,
		arg.Village,
		arg.ContactNo,
		arg.DrugAllergies,
		arg.ID,
	)
	return err
}

const upsertDental = `-- name: UpsertDental :exec
INSERT INTO dental (
  id,
  vid,
  fluoride_exposure,
  diet,
  bacterial_exposure,
  oral_symptoms,
  drink_other_water,
  risk_for_dental_carries,
  icope_difficulty_chewing,
  icope_pain_in_mouth,
  dental_notes
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (id, vid) DO UPDATE SET
  fluoride_exposure      = EXCLUDED.fluoride_exposure,
  diet                   = EXCLUDED.diet,
  bacterial_exposure     = EXCLUDED.bacterial_exposure,
  oral_symptoms          = EXCLUDED.oral_symptoms,
  drink_other_water      = EXCLUDED.drink_other_water,
  risk_for_dental_carries = EXCLUDED.risk_for_dental_carries,
  icope_difficulty_chewing = EXCLUDED.icope_difficulty_chewing,
  icope_pain_in_mouth    = EXCLUDED.icope_pain_in_mouth,
  dental_notes           = EXCLUDED.dental_notes
`

type UpsertDentalParams struct {
	ID                     int32   `json:"id"`
	Vid                    int32   `json:"vid"`
	FluorideExposure       string  `json:"fluoride_exposure"`
	Diet                   string  `json:"diet"`
	BacterialExposure      string  `json:"bacterial_exposure"`
	OralSymptoms           bool    `json:"oral_symptoms"`
	DrinkOtherWater        bool    `json:"drink_other_water"`
	RiskForDentalCarries   string  `json:"risk_for_dental_carries"`
	IcopeDifficultyChewing *bool   `json:"icope_difficulty_chewing"`
	IcopePainInMouth       *bool   `json:"icope_pain_in_mouth"`
	DentalNotes            *string `json:"dental_notes"`
}

func (q *Queries) UpsertDental(ctx context.Context, arg UpsertDentalParams) error {
	_, err := q.db.Exec(ctx, upsertDental,
		arg.ID,
		arg.Vid,
		arg.FluorideExposure,
		arg.Diet,
		arg.BacterialExposure,
		arg.OralSymptoms,
		arg.DrinkOtherWater,
		arg.RiskForDentalCarries,
		arg.IcopeDifficultyChewing,
		arg.IcopePainInMouth,
		arg.DentalNotes,
	)
	return err
}

const upsertDoctorsConsultation = `-- name: UpsertDoctorsConsultation :exec
INSERT INTO doctors_consultation (
  id,
  vid,
  well,
  msk,
  cvs,
  respi,
  gu,
  git,
  eye,
  derm,
  others,
  consultation_notes,
  diagnosis,
  treatment,
  referral_needed,
  referral_loc,
  remarks
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
ON CONFLICT (id, vid) DO UPDATE SET
  well               = EXCLUDED.well,
  msk                = EXCLUDED.msk,
  cvs                = EXCLUDED.cvs,
  respi              = EXCLUDED.respi,
  gu                 = EXCLUDED.gu,
  git                = EXCLUDED.git,
  eye                = EXCLUDED.eye,
  derm               = EXCLUDED.derm,
  others             = EXCLUDED.others,
  consultation_notes = EXCLUDED.consultation_notes,
  diagnosis          = EXCLUDED.diagnosis,
  treatment          = EXCLUDED.treatment,
  referral_needed    = EXCLUDED.referral_needed,
  referral_loc       = EXCLUDED.referral_loc,
  remarks            = EXCLUDED.remarks
`

type UpsertDoctorsConsultationParams struct {
	ID                int32   `json:"id"`
	Vid               int32   `json:"vid"`
	Well              *bool   `json:"well"`
	Msk               *bool   `json:"msk"`
	Cvs               *bool   `json:"cvs"`
	Respi             *bool   `json:"respi"`
	Gu                *bool   `json:"gu"`
	Git               *bool   `json:"git"`
	Eye               *bool   `json:"eye"`
	Derm              *bool   `json:"derm"`
	Others            *string `json:"others"`
	ConsultationNotes *string `json:"consultation_notes"`
	Diagnosis         *string `json:"diagnosis"`
	Treatment         *string `json:"treatment"`
	ReferralNeeded    bool    `json:"referral_needed"`
	ReferralLoc       *string `json:"referral_loc"`
	Remarks           *string `json:"remarks"`
}

func (q *Queries) UpsertDoctorsConsultation(ctx context.Context, arg UpsertDoctorsConsultationParams) error {
	_, err := q.db.Exec(ctx, upsertDoctorsConsultation,
		arg.ID,
		arg.Vid,
		arg.Well,
		arg.Msk,
		arg.Cvs,
		arg.Respi,
		arg.Gu,
		arg.Git,
		arg.Eye,
		arg.Derm,
		arg.Others,
		arg.ConsultationNotes,
		arg.Diagnosis,
		arg.Treatment,
		arg.ReferralNeeded,
		arg.ReferralLoc,
		arg.Remarks,
	)
	return err
}

const upsertFallRisk = `-- name: UpsertFallRisk :exec
INSERT INTO fall_risk (
  id,
  vid,
  side_to_side_balance,
  semi_tandem_balance,
  tandem_balance,
  gait_speed_test,
  chair_stand_test,
  fall_risk_score,
  icope_complete_chair_stands,
  icope_chair_stands_time
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (id, vid) DO UPDATE SET
  side_to_side_balance   = EXCLUDED.side_to_side_balance,
  semi_tandem_balance    = EXCLUDED.semi_tandem_balance,
  tandem_balance         = EXCLUDED.tandem_balance,
  gait_speed_test        = EXCLUDED.gait_speed_test,
  chair_stand_test       = EXCLUDED.chair_stand_test,
  fall_risk_score        = EXCLUDED.fall_risk_score,
  icope_complete_chair_stands = EXCLUDED.icope_complete_chair_stands,
  icope_chair_stands_time = EXCLUDED.icope_chair_stands_time
`

type UpsertFallRiskParams struct {
	ID                       int32 `json:"id"`
	Vid                      int32 `json:"vid"`
	SideToSideBalance        int32 `json:"side_to_side_balance"`
	SemiTandemBalance        int32 `json:"semi_tandem_balance"`
	TandemBalance            int32 `json:"tandem_balance"`
	GaitSpeedTest            int32 `json:"gait_speed_test"`
	ChairStandTest           int32 `json:"chair_stand_test"`
	FallRiskScore            int32 `json:"fall_risk_score"`
	IcopeCompleteChairStands *bool `json:"icope_complete_chair_stands"`
	IcopeChairStandsTime     *bool `json:"icope_chair_stands_time"`
}

func (q *Queries) UpsertFallRisk(ctx context.Context, arg UpsertFallRiskParams) error {
	_, err := q.db.Exec(ctx, upsertFallRisk,
		arg.ID,
		arg.Vid,
		arg.SideToSideBalance,
		arg.SemiTandemBalance,
		arg.TandemBalance,
		arg.GaitSpeedTest,
		arg.ChairStandTest,
		arg.FallRiskScore,
		arg.IcopeCompleteChairStands,
		arg.IcopeChairStandsTime,
	)
	return err
}

const upsertHeightAndWeight = `-- name: UpsertHeightAndWeight :exec
INSERT INTO height_and_weight (
  id,
  vid,
  height,
  weight,
  bmi,
  bmi_analysis,
  paeds_height,
  paeds_weight,
  icope_lost_weight_past_months,
  icope_no_desire_to_eat
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (id, vid) DO UPDATE SET
  height                     = EXCLUDED.height,
  weight                     = EXCLUDED.weight,
  bmi                        = EXCLUDED.bmi,
  bmi_analysis               = EXCLUDED.bmi_analysis,
  paeds_height               = EXCLUDED.paeds_height,
  paeds_weight               = EXCLUDED.paeds_weight,
  icope_lost_weight_past_months = EXCLUDED.icope_lost_weight_past_months,
  icope_no_desire_to_eat     = EXCLUDED.icope_no_desire_to_eat
`

type UpsertHeightAndWeightParams struct {
	ID                        int32          `json:"id"`
	Vid                       int32          `json:"vid"`
	Height                    pgtype.Numeric `json:"height"`
	Weight                    pgtype.Numeric `json:"weight"`
	Bmi                       pgtype.Numeric `json:"bmi"`
	BmiAnalysis               string         `json:"bmi_analysis"`
	PaedsHeight               pgtype.Numeric `json:"paeds_height"`
	PaedsWeight               pgtype.Numeric `json:"paeds_weight"`
	IcopeLostWeightPastMonths *bool          `json:"icope_lost_weight_past_months"`
	IcopeNoDesireToEat        *bool          `json:"icope_no_desire_to_eat"`
}

func (q *Queries) UpsertHeightAndWeight(ctx context.Context, arg UpsertHeightAndWeightParams) error {
	_, err := q.db.Exec(ctx, upsertHeightAndWeight,
		arg.ID,
		arg.Vid,
		arg.Height,
		arg.Weight,
		arg.Bmi,
		arg.BmiAnalysis,
		arg.PaedsHeight,
		arg.PaedsWeight,
		arg.IcopeLostWeightPastMonths,
		arg.IcopeNoDesireToEat,
	)
	return err
}

const upsertPastMedicalHistory = `-- name: UpsertPastMedicalHistory :exec
INSERT INTO past_medical_history (
  id,
  vid,
  cough,
  fever,
  blocked_nose,
  sore_throat,
  night_sweats,
  unintentional_weight_loss,
  tuberculosis,
  tuberculosis_has_been_treated,
  diabetes,
  hypertension,
  hyperlipidemia,
  chronic_joint_pains,
  chronic_muscle_aches,
  sexually_transmitted_disease,
  specified_stds,
  others
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
ON CONFLICT (id, vid) DO UPDATE SET
  cough                       = EXCLUDED.cough,
  fever                       = EXCLUDED.fever,
  blocked_nose                = EXCLUDED.blocked_nose,
  sore_throat                 = EXCLUDED.sore_throat,
  night_sweats                = EXCLUDED.night_sweats,
  unintentional_weight_loss   = EXCLUDED.unintentional_weight_loss,
  tuberculosis                = EXCLUDED.tuberculosis,
  tuberculosis_has_been_treated = EXCLUDED.tuberculosis_has_been_treated,
  diabetes                    = EXCLUDED.diabetes,
  hypertension                = EXCLUDED.hypertension,
  hyperlipidemia              = EXCLUDED.hyperlipidemia,
  chronic_joint_pains         = EXCLUDED.chronic_joint_pains,
  chronic_muscle_aches        = EXCLUDED.chronic_muscle_aches,
  sexually_transmitted_disease = EXCLUDED.sexually_transmitted_disease,
  specified_stds              = EXCLUDED.specified_stds,
  others                      = EXCLUDED.others
`

type UpsertPastMedicalHistoryParams struct {
	ID                         int32   `json:"id"`
	Vid                        int32   `json:"vid"`
	Cough                      *bool   `json:"cough"`
	Fever                      *bool   `json:"fever"`
	BlockedNose                *bool   `json:"blocked_nose"`
	SoreThroat                 *bool   `json:"sore_throat"`
	NightSweats                *bool   `json:"night_sweats"`
	UnintentionalWeightLoss    *bool   `json:"unintentional_weight_loss"`
	Tuberculosis               *bool   `json:"tuberculosis"`
	TuberculosisHasBeenTreated *bool   `json:"tuberculosis_has_been_treated"`
	Diabetes                   *bool   `json:"diabetes"`
	Hypertension               *bool   `json:"hypertension"`
	Hyperlipidemia             *bool   `json:"hyperlipidemia"`
	ChronicJointPains          *bool   `json:"chronic_joint_pains"`
	ChronicMuscleAches         *bool   `json:"chronic_muscle_aches"`
	SexuallyTransmittedDisease *bool   `json:"sexually_transmitted_disease"`
	SpecifiedStds              *string `json:"specified_stds"`
	Others                     *string `json:"others"`
}

func (q *Queries) UpsertPastMedicalHistory(ctx context.Context, arg UpsertPastMedicalHistoryParams) error {
	_, err := q.db.Exec(ctx, upsertPastMedicalHistory,
		arg.ID,
		arg.Vid,
		arg.Cough,
		arg.Fever,
		arg.BlockedNose,
		arg.SoreThroat,
		arg.NightSweats,
		arg.UnintentionalWeightLoss,
		arg.Tuberculosis,
		arg.TuberculosisHasBeenTreated,
		arg.Diabetes,
		arg.Hypertension,
		arg.Hyperlipidemia,
		arg.ChronicJointPains,
		arg.ChronicMuscleAches,
		arg.SexuallyTransmittedDisease,
		arg.SpecifiedStds,
		arg.Others,
	)
	return err
}

const upsertPhysiotherapy = `-- name: UpsertPhysiotherapy :exec
INSERT INTO physiotherapy (
  id,
  vid,
  subjective_assessment,
  pain_scale,
  objective_assessment,
  intervention,
  evaluation
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (id, vid) DO UPDATE SET
  subjective_assessment = EXCLUDED.subjective_assessment,
  pain_scale            = EXCLUDED.pain_scale,
  objective_assessment  = EXCLUDED.objective_assessment,
  intervention          = EXCLUDED.intervention,
  evaluation            = EXCLUDED.evaluation
`

type UpsertPhysiotherapyParams struct {
	ID                   int32   `json:"id"`
	Vid                  int32   `json:"vid"`
	SubjectiveAssessment *string `json:"subjective_assessment"`
	PainScale            *int32  `json:"pain_scale"`
	ObjectiveAssessment  *string `json:"objective_assessment"`
	Intervention         *string `json:"intervention"`
	Evaluation           *string `json:"evaluation"`
}

func (q *Queries) UpsertPhysiotherapy(ctx context.Context, arg UpsertPhysiotherapyParams) error {
	_, err := q.db.Exec(ctx, upsertPhysiotherapy,
		arg.ID,
		arg.Vid,
		arg.SubjectiveAssessment,
		arg.PainScale,
		arg.ObjectiveAssessment,
		arg.Intervention,
		arg.Evaluation,
	)
	return err
}

const upsertSocialHistory = `-- name: UpsertSocialHistory :exec
INSERT INTO social_history (
  id,
  vid,
  past_smoking_history,
  no_of_years,
  current_smoking_history,
  cigarettes_per_day,
  alcohol_history,
  how_regular
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (id, vid) DO UPDATE SET
  past_smoking_history = EXCLUDED.past_smoking_history,
  no_of_years          = EXCLUDED.no_of_years,
  current_smoking_history = EXCLUDED.current_smoking_history,
  cigarettes_per_day   = EXCLUDED.cigarettes_per_day,
  alcohol_history      = EXCLUDED.alcohol_history,
  how_regular          = EXCLUDED.how_regular
`

type UpsertSocialHistoryParams struct {
	ID                    int32   `json:"id"`
	Vid                   int32   `json:"vid"`
	PastSmokingHistory    bool    `json:"past_smoking_history"`
	NoOfYears             *int32  `json:"no_of_years"`
	CurrentSmokingHistory bool    `json:"current_smoking_history"`
	CigarettesPerDay      *int32  `json:"cigarettes_per_day"`
	AlcoholHistory        bool    `json:"alcohol_history"`
	HowRegular            *string `json:"how_regular"`
}

func (q *Queries) UpsertSocialHistory(ctx context.Context, arg UpsertSocialHistoryParams) error {
	_, err := q.db.Exec(ctx, upsertSocialHistory,
		arg.ID,
		arg.Vid,
		arg.PastSmokingHistory,
		arg.NoOfYears,
		arg.CurrentSmokingHistory,
		arg.CigarettesPerDay,
		arg.AlcoholHistory,
		arg.HowRegular,
	)
	return err
}

const upsertVisualAcuity = `-- name: UpsertVisualAcuity :exec
INSERT INTO visual_acuity (
  id,
  vid,
  l_eye_vision,
  r_eye_vision,
  additional_intervention,
  sent_to_opto,
  referred_for_glasses,
  icope_eye_problem,
  icope_treated_for_diabetes_or_bp
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (id, vid) DO UPDATE SET
  l_eye_vision                = EXCLUDED.l_eye_vision,
  r_eye_vision                = EXCLUDED.r_eye_vision,
  additional_intervention     = EXCLUDED.additional_intervention,
  sent_to_opto                = EXCLUDED.sent_to_opto,
  referred_for_glasses        = EXCLUDED.referred_for_glasses,
  icope_eye_problem           = EXCLUDED.icope_eye_problem,
  icope_treated_for_diabetes_or_bp = EXCLUDED.icope_treated_for_diabetes_or_bp
`

type UpsertVisualAcuityParams struct {
	ID                          int32   `json:"id"`
	Vid                         int32   `json:"vid"`
	LEyeVision                  int32   `json:"l_eye_vision"`
	REyeVision                  int32   `json:"r_eye_vision"`
	AdditionalIntervention      *string `json:"additional_intervention"`
	SentToOpto                  bool    `json:"sent_to_opto"`
	ReferredForGlasses          bool    `json:"referred_for_glasses"`
	IcopeEyeProblem             *bool   `json:"icope_eye_problem"`
	IcopeTreatedForDiabetesOrBp *bool   `json:"icope_treated_for_diabetes_or_bp"`
}

func (q *Queries) UpsertVisualAcuity(ctx context.Context, arg UpsertVisualAcuityParams) error {
	_, err := q.db.Exec(ctx, upsertVisualAcuity,
		arg.ID,
		arg.Vid,
		arg.LEyeVision,
		arg.REyeVision,
		arg.AdditionalIntervention,
		arg.SentToOpto,
		arg.ReferredForGlasses,
		arg.IcopeEyeProblem,
		arg.IcopeTreatedForDiabetesOrBp,
	)
	return err
}

const upsertVitalStatistics = `-- name: UpsertVitalStatistics :exec
INSERT INTO vital_statistics (
  id,
  vid,
  temperature,
  spo2,
  systolic_bp1,
  diastolic_bp1,
  systolic_bp2,
  diastolic_bp2,
  avg_systolic_bp,
  avg_diastolic_bp,
  hr1,
  hr2,
  avg_hr,
  rand_blood_glucose_mmol_l,
  icope_high_bp
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
ON CONFLICT (id, vid) DO UPDATE SET
  temperature              = EXCLUDED.temperature,
  spo2                     = EXCLUDED.spo2,
  systolic_bp1             = EXCLUDED.systolic_bp1,
  diastolic_bp1            = EXCLUDED.diastolic_bp1,
  systolic_bp2             = EXCLUDED.systolic_bp2,
  diastolic_bp2            = EXCLUDED.diastolic_bp2,
  avg_systolic_bp          = EXCLUDED.avg_systolic_bp,
  avg_diastolic_bp         = EXCLUDED.avg_diastolic_bp,
  hr1                      = EXCLUDED.hr1,
  hr2                      = EXCLUDED.hr2,
  avg_hr                   = EXCLUDED.avg_hr,
  rand_blood_glucose_mmol_l = EXCLUDED.rand_blood_glucose_mmol_l,
  icope_high_bp            = EXCLUDED.icope_high_bp
`

type UpsertVitalStatisticsParams struct {
	ID                    int32          `json:"id"`
	Vid                   int32          `json:"vid"`
	Temperature           pgtype.Numeric `json:"temperature"`
	Spo2                  pgtype.Numeric `json:"spo2"`
	SystolicBp1           pgtype.Numeric `json:"systolic_bp1"`
	DiastolicBp1          pgtype.Numeric `json:"diastolic_bp1"`
	SystolicBp2           pgtype.Numeric `json:"systolic_bp2"`
	DiastolicBp2          pgtype.Numeric `json:"diastolic_bp2"`
	AvgSystolicBp         pgtype.Numeric `json:"avg_systolic_bp"`
	AvgDiastolicBp        pgtype.Numeric `json:"avg_diastolic_bp"`
	Hr1                   pgtype.Numeric `json:"hr1"`
	Hr2                   pgtype.Numeric `json:"hr2"`
	AvgHr                 pgtype.Numeric `json:"avg_hr"`
	RandBloodGlucoseMmolL pgtype.Numeric `json:"rand_blood_glucose_mmol_l"`
	IcopeHighBp           *bool          `json:"icope_high_bp"`
}

func (q *Queries) UpsertVitalStatistics(ctx context.Context, arg UpsertVitalStatisticsParams) error {
	_, err := q.db.Exec(ctx, upsertVitalStatistics,
		arg.ID,
		arg.Vid,
		arg.Temperature,
		arg.Spo2,
		arg.SystolicBp1,
		arg.DiastolicBp1,
		arg.SystolicBp2,
		arg.DiastolicBp2,
		arg.AvgSystolicBp,
		arg.AvgDiastolicBp,
		arg.Hr1,
		arg.Hr2,
		arg.AvgHr,
		arg.RandBloodGlucoseMmolL,
		arg.IcopeHighBp,
	)
	return err
}
