// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pharmacy.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPrescriptionAllocationsForBatch = `-- name: CountPrescriptionAllocationsForBatch :one
SELECT COUNT(*) AS cnt
FROM prescription_batch_items pbi
JOIN batch_locations bl ON bl.id = pbi.batch_location_id
WHERE bl.batch_id = $1
`

func (q *Queries) CountPrescriptionAllocationsForBatch(ctx context.Context, batchID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPrescriptionAllocationsForBatch, batchID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countPrescriptionAllocationsForLocation = `-- name: CountPrescriptionAllocationsForLocation :one
SELECT COUNT(*) AS cnt
FROM prescription_batch_items
WHERE batch_location_id = $1
`

func (q *Queries) CountPrescriptionAllocationsForLocation(ctx context.Context, batchLocationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPrescriptionAllocationsForLocation, batchLocationID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countPrescriptionLinesForDrug = `-- name: CountPrescriptionLinesForDrug :one
SELECT COUNT(*) AS cnt
FROM prescription_lines
WHERE drug_id = $1
`

func (q *Queries) CountPrescriptionLinesForDrug(ctx context.Context, drugID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPrescriptionLinesForDrug, drugID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const deleteBatch = `-- name: DeleteBatch :exec
DELETE FROM drug_batches WHERE id=$1
`

func (q *Queries) DeleteBatch(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBatch, id)
	return err
}

const deleteBatchLocation = `-- name: DeleteBatchLocation :exec
DELETE FROM batch_locations WHERE id=$1
`

func (q *Queries) DeleteBatchLocation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBatchLocation, id)
	return err
}

const deleteDrug = `-- name: DeleteDrug :exec
DELETE FROM drugs WHERE id=$1
`

func (q *Queries) DeleteDrug(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDrug, id)
	return err
}

const getBatch = `-- name: GetBatch :one
SELECT id, drug_id, batch_number, expiry_date, supplier, quantity, created_at, updated_at
FROM drug_batches
WHERE id = $1
`

type GetBatchRow struct {
	ID          int64      `json:"id"`
	DrugID      int64      `json:"drug_id"`
	BatchNumber string     `json:"batch_number"`
	ExpiryDate  *time.Time `json:"expiry_date"`
	Supplier    *string    `json:"supplier"`
	Quantity    int32      `json:"quantity"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   *time.Time `json:"updated_at"`
}

func (q *Queries) GetBatch(ctx context.Context, id int64) (GetBatchRow, error) {
	row := q.db.QueryRow(ctx, getBatch, id)
	var i GetBatchRow
	err := row.Scan(
		&i.ID,
		&i.DrugID,
		&i.BatchNumber,
		&i.ExpiryDate,
		&i.Supplier,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBatchLocation = `-- name: GetBatchLocation :one
SELECT id, batch_id, location, quantity, created_at, updated_at
FROM batch_locations
WHERE id = $1
`

type GetBatchLocationRow struct {
	ID        int64      `json:"id"`
	BatchID   int64      `json:"batch_id"`
	Location  string     `json:"location"`
	Quantity  int32      `json:"quantity"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

func (q *Queries) GetBatchLocation(ctx context.Context, id int64) (GetBatchLocationRow, error) {
	row := q.db.QueryRow(ctx, getBatchLocation, id)
	var i GetBatchLocationRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Location,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDrug = `-- name: GetDrug :one
SELECT id, generic_name, brand_name, drug_code, dosage_form_code, route_code,
       strength_num, strength_unit_num, strength_den, strength_unit_den,
       dispense_unit, piece_content_amount, piece_content_unit,
       is_fractional_allowed, display_as_percentage, barcode, notes, is_active, created_at, updated_at
FROM drugs
WHERE id = $1
`

type GetDrugRow struct {
	ID                  int64          `json:"id"`
	GenericName         string         `json:"generic_name"`
	BrandName           *string        `json:"brand_name"`
	DrugCode            *int32         `json:"drug_code"`
	DosageFormCode      string         `json:"dosage_form_code"`
	RouteCode           string         `json:"route_code"`
	StrengthNum         pgtype.Numeric `json:"strength_num"`
	StrengthUnitNum     *string        `json:"strength_unit_num"`
	StrengthDen         pgtype.Numeric `json:"strength_den"`
	StrengthUnitDen     *string        `json:"strength_unit_den"`
	DispenseUnit        string         `json:"dispense_unit"`
	PieceContentAmount  pgtype.Numeric `json:"piece_content_amount"`
	PieceContentUnit    *string        `json:"piece_content_unit"`
	IsFractionalAllowed *bool          `json:"is_fractional_allowed"`
	DisplayAsPercentage *bool          `json:"display_as_percentage"`
	Barcode             *string        `json:"barcode"`
	Notes               *string        `json:"notes"`
	IsActive            bool           `json:"is_active"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           *time.Time     `json:"updated_at"`
}

func (q *Queries) GetDrug(ctx context.Context, id int64) (GetDrugRow, error) {
	row := q.db.QueryRow(ctx, getDrug, id)
	var i GetDrugRow
	err := row.Scan(
		&i.ID,
		&i.GenericName,
		&i.BrandName,
		&i.DrugCode,
		&i.DosageFormCode,
		&i.RouteCode,
		&i.StrengthNum,
		&i.StrengthUnitNum,
		&i.StrengthDen,
		&i.StrengthUnitDen,
		&i.DispenseUnit,
		&i.PieceContentAmount,
		&i.PieceContentUnit,
		&i.IsFractionalAllowed,
		&i.DisplayAsPercentage,
		&i.Barcode,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBatch = `-- name: InsertBatch :one
INSERT INTO drug_batches (drug_id, batch_number, expiry_date, supplier, quantity)
VALUES ($1,$2,$3,$4,COALESCE($5,0))
RETURNING id
`

type InsertBatchParams struct {
	DrugID      int64       `json:"drug_id"`
	BatchNumber string      `json:"batch_number"`
	ExpiryDate  *time.Time  `json:"expiry_date"`
	Supplier    *string     `json:"supplier"`
	Column5     interface{} `json:"column_5"`
}

func (q *Queries) InsertBatch(ctx context.Context, arg InsertBatchParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertBatch,
		arg.DrugID,
		arg.BatchNumber,
		arg.ExpiryDate,
		arg.Supplier,
		arg.Column5,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertBatchLocation = `-- name: InsertBatchLocation :one
INSERT INTO batch_locations (batch_id, location, quantity)
VALUES ($1,$2,$3)
RETURNING id, created_at, updated_at
`

type InsertBatchLocationParams struct {
	BatchID  int64  `json:"batch_id"`
	Location string `json:"location"`
	Quantity int32  `json:"quantity"`
}

type InsertBatchLocationRow struct {
	ID        int64      `json:"id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

func (q *Queries) InsertBatchLocation(ctx context.Context, arg InsertBatchLocationParams) (InsertBatchLocationRow, error) {
	row := q.db.QueryRow(ctx, insertBatchLocation, arg.BatchID, arg.Location, arg.Quantity)
	var i InsertBatchLocationRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const insertDrug = `-- name: InsertDrug :one
INSERT INTO drugs (
  generic_name, brand_name, drug_code, dosage_form_code, route_code,
  strength_num, strength_unit_num, strength_den, strength_unit_den,
  dispense_unit, piece_content_amount, piece_content_unit,
  is_fractional_allowed, display_as_percentage, barcode, notes, is_active
) VALUES (
  $1,$2,$3,$4,$5,
  $6,$7,$8,$9,
  $10,$11,$12,
  COALESCE($13,FALSE),COALESCE($14,FALSE),$15,$16,COALESCE($17,TRUE)
) RETURNING id
`

type InsertDrugParams struct {
	GenericName        string         `json:"generic_name"`
	BrandName          *string        `json:"brand_name"`
	DrugCode           *int32         `json:"drug_code"`
	DosageFormCode     string         `json:"dosage_form_code"`
	RouteCode          string         `json:"route_code"`
	StrengthNum        pgtype.Numeric `json:"strength_num"`
	StrengthUnitNum    *string        `json:"strength_unit_num"`
	StrengthDen        pgtype.Numeric `json:"strength_den"`
	StrengthUnitDen    *string        `json:"strength_unit_den"`
	DispenseUnit       string         `json:"dispense_unit"`
	PieceContentAmount pgtype.Numeric `json:"piece_content_amount"`
	PieceContentUnit   *string        `json:"piece_content_unit"`
	Column13           interface{}    `json:"column_13"`
	Column14           interface{}    `json:"column_14"`
	Barcode            *string        `json:"barcode"`
	Notes              *string        `json:"notes"`
	Column17           interface{}    `json:"column_17"`
}

func (q *Queries) InsertDrug(ctx context.Context, arg InsertDrugParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertDrug,
		arg.GenericName,
		arg.BrandName,
		arg.DrugCode,
		arg.DosageFormCode,
		arg.RouteCode,
		arg.StrengthNum,
		arg.StrengthUnitNum,
		arg.StrengthDen,
		arg.StrengthUnitDen,
		arg.DispenseUnit,
		arg.PieceContentAmount,
		arg.PieceContentUnit,
		arg.Column13,
		arg.Column14,
		arg.Barcode,
		arg.Notes,
		arg.Column17,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listBatchLocationsByBatch = `-- name: ListBatchLocationsByBatch :many
SELECT id, batch_id, location, quantity, created_at, updated_at
FROM batch_locations
WHERE batch_id = $1
ORDER BY location, id
`

type ListBatchLocationsByBatchRow struct {
	ID        int64      `json:"id"`
	BatchID   int64      `json:"batch_id"`
	Location  string     `json:"location"`
	Quantity  int32      `json:"quantity"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

func (q *Queries) ListBatchLocationsByBatch(ctx context.Context, batchID int64) ([]ListBatchLocationsByBatchRow, error) {
	rows, err := q.db.Query(ctx, listBatchLocationsByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBatchLocationsByBatchRow
	for rows.Next() {
		var i ListBatchLocationsByBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.Location,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBatchLocationsByBatchIDs = `-- name: ListBatchLocationsByBatchIDs :many
SELECT id, batch_id, location, quantity, created_at, updated_at
FROM batch_locations
WHERE batch_id = ANY($1::bigint[])
ORDER BY batch_id, location, id
`

type ListBatchLocationsByBatchIDsRow struct {
	ID        int64      `json:"id"`
	BatchID   int64      `json:"batch_id"`
	Location  string     `json:"location"`
	Quantity  int32      `json:"quantity"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

func (q *Queries) ListBatchLocationsByBatchIDs(ctx context.Context, dollar_1 []int64) ([]ListBatchLocationsByBatchIDsRow, error) {
	rows, err := q.db.Query(ctx, listBatchLocationsByBatchIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBatchLocationsByBatchIDsRow
	for rows.Next() {
		var i ListBatchLocationsByBatchIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.Location,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBatchesByDrug = `-- name: ListBatchesByDrug :many

SELECT id, drug_id, batch_number, expiry_date, supplier, quantity, created_at, updated_at
FROM drug_batches
WHERE drug_id = $1
ORDER BY expiry_date NULLS LAST, batch_number, id
`

type ListBatchesByDrugRow struct {
	ID          int64      `json:"id"`
	DrugID      int64      `json:"drug_id"`
	BatchNumber string     `json:"batch_number"`
	ExpiryDate  *time.Time `json:"expiry_date"`
	Supplier    *string    `json:"supplier"`
	Quantity    int32      `json:"quantity"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   *time.Time `json:"updated_at"`
}

// Batches --------------------------------------------------------------------
func (q *Queries) ListBatchesByDrug(ctx context.Context, drugID int64) ([]ListBatchesByDrugRow, error) {
	rows, err := q.db.Query(ctx, listBatchesByDrug, drugID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBatchesByDrugRow
	for rows.Next() {
		var i ListBatchesByDrugRow
		if err := rows.Scan(
			&i.ID,
			&i.DrugID,
			&i.BatchNumber,
			&i.ExpiryDate,
			&i.Supplier,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrugs = `-- name: ListDrugs :many

SELECT id, generic_name, brand_name, drug_code, dosage_form_code, route_code,
       strength_num, strength_unit_num, strength_den, strength_unit_den,
       dispense_unit, piece_content_amount, piece_content_unit,
       is_fractional_allowed, display_as_percentage, barcode, notes, is_active, created_at, updated_at
FROM drugs
ORDER BY generic_name, COALESCE(brand_name, ''), dosage_form_code, route_code
`

type ListDrugsRow struct {
	ID                  int64          `json:"id"`
	GenericName         string         `json:"generic_name"`
	BrandName           *string        `json:"brand_name"`
	DrugCode            *int32         `json:"drug_code"`
	DosageFormCode      string         `json:"dosage_form_code"`
	RouteCode           string         `json:"route_code"`
	StrengthNum         pgtype.Numeric `json:"strength_num"`
	StrengthUnitNum     *string        `json:"strength_unit_num"`
	StrengthDen         pgtype.Numeric `json:"strength_den"`
	StrengthUnitDen     *string        `json:"strength_unit_den"`
	DispenseUnit        string         `json:"dispense_unit"`
	PieceContentAmount  pgtype.Numeric `json:"piece_content_amount"`
	PieceContentUnit    *string        `json:"piece_content_unit"`
	IsFractionalAllowed *bool          `json:"is_fractional_allowed"`
	DisplayAsPercentage *bool          `json:"display_as_percentage"`
	Barcode             *string        `json:"barcode"`
	Notes               *string        `json:"notes"`
	IsActive            bool           `json:"is_active"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           *time.Time     `json:"updated_at"`
}

// Drugs ----------------------------------------------------------------------
func (q *Queries) ListDrugs(ctx context.Context) ([]ListDrugsRow, error) {
	rows, err := q.db.Query(ctx, listDrugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDrugsRow
	for rows.Next() {
		var i ListDrugsRow
		if err := rows.Scan(
			&i.ID,
			&i.GenericName,
			&i.BrandName,
			&i.DrugCode,
			&i.DosageFormCode,
			&i.RouteCode,
			&i.StrengthNum,
			&i.StrengthUnitNum,
			&i.StrengthDen,
			&i.StrengthUnitDen,
			&i.DispenseUnit,
			&i.PieceContentAmount,
			&i.PieceContentUnit,
			&i.IsFractionalAllowed,
			&i.DisplayAsPercentage,
			&i.Barcode,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDrugs = `-- name: SearchDrugs :many
SELECT id, generic_name, brand_name, drug_code, dosage_form_code, route_code,
       strength_num, strength_unit_num, strength_den, strength_unit_den,
       dispense_unit, piece_content_amount, piece_content_unit,
       is_fractional_allowed, display_as_percentage, barcode, notes, is_active, created_at, updated_at
FROM drugs
WHERE generic_name ILIKE $1 OR COALESCE(brand_name, '') ILIKE $1
ORDER BY generic_name, COALESCE(brand_name, ''), dosage_form_code, route_code
`

type SearchDrugsRow struct {
	ID                  int64          `json:"id"`
	GenericName         string         `json:"generic_name"`
	BrandName           *string        `json:"brand_name"`
	DrugCode            *int32         `json:"drug_code"`
	DosageFormCode      string         `json:"dosage_form_code"`
	RouteCode           string         `json:"route_code"`
	StrengthNum         pgtype.Numeric `json:"strength_num"`
	StrengthUnitNum     *string        `json:"strength_unit_num"`
	StrengthDen         pgtype.Numeric `json:"strength_den"`
	StrengthUnitDen     *string        `json:"strength_unit_den"`
	DispenseUnit        string         `json:"dispense_unit"`
	PieceContentAmount  pgtype.Numeric `json:"piece_content_amount"`
	PieceContentUnit    *string        `json:"piece_content_unit"`
	IsFractionalAllowed *bool          `json:"is_fractional_allowed"`
	DisplayAsPercentage *bool          `json:"display_as_percentage"`
	Barcode             *string        `json:"barcode"`
	Notes               *string        `json:"notes"`
	IsActive            bool           `json:"is_active"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           *time.Time     `json:"updated_at"`
}

func (q *Queries) SearchDrugs(ctx context.Context, genericName string) ([]SearchDrugsRow, error) {
	rows, err := q.db.Query(ctx, searchDrugs, genericName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDrugsRow
	for rows.Next() {
		var i SearchDrugsRow
		if err := rows.Scan(
			&i.ID,
			&i.GenericName,
			&i.BrandName,
			&i.DrugCode,
			&i.DosageFormCode,
			&i.RouteCode,
			&i.StrengthNum,
			&i.StrengthUnitNum,
			&i.StrengthDen,
			&i.StrengthUnitDen,
			&i.DispenseUnit,
			&i.PieceContentAmount,
			&i.PieceContentUnit,
			&i.IsFractionalAllowed,
			&i.DisplayAsPercentage,
			&i.Barcode,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBatch = `-- name: UpdateBatch :exec
UPDATE drug_batches
SET batch_number=$2, expiry_date=$3, supplier=$4
WHERE id=$1
`

type UpdateBatchParams struct {
	ID          int64      `json:"id"`
	BatchNumber string     `json:"batch_number"`
	ExpiryDate  *time.Time `json:"expiry_date"`
	Supplier    *string    `json:"supplier"`
}

func (q *Queries) UpdateBatch(ctx context.Context, arg UpdateBatchParams) error {
	_, err := q.db.Exec(ctx, updateBatch,
		arg.ID,
		arg.BatchNumber,
		arg.ExpiryDate,
		arg.Supplier,
	)
	return err
}

const updateBatchLocation = `-- name: UpdateBatchLocation :exec
UPDATE batch_locations
SET location=$2, quantity=$3, updated_at=NOW()
WHERE id=$1
`

type UpdateBatchLocationParams struct {
	ID       int64  `json:"id"`
	Location string `json:"location"`
	Quantity int32  `json:"quantity"`
}

func (q *Queries) UpdateBatchLocation(ctx context.Context, arg UpdateBatchLocationParams) error {
	_, err := q.db.Exec(ctx, updateBatchLocation, arg.ID, arg.Location, arg.Quantity)
	return err
}

const updateDrug = `-- name: UpdateDrug :exec
UPDATE drugs SET
  generic_name=$2, brand_name=$3, drug_code=$4,
  dosage_form_code=$5, route_code=$6,
  strength_num=$7, strength_unit_num=$8, strength_den=$9, strength_unit_den=$10,
  dispense_unit=$11, piece_content_amount=$12, piece_content_unit=$13,
  is_fractional_allowed=$14, display_as_percentage=$15, barcode=$16, notes=$17, is_active=$18, updated_at=NOW()
WHERE id=$1
`

type UpdateDrugParams struct {
	ID                  int64          `json:"id"`
	GenericName         string         `json:"generic_name"`
	BrandName           *string        `json:"brand_name"`
	DrugCode            *int32         `json:"drug_code"`
	DosageFormCode      string         `json:"dosage_form_code"`
	RouteCode           string         `json:"route_code"`
	StrengthNum         pgtype.Numeric `json:"strength_num"`
	StrengthUnitNum     *string        `json:"strength_unit_num"`
	StrengthDen         pgtype.Numeric `json:"strength_den"`
	StrengthUnitDen     *string        `json:"strength_unit_den"`
	DispenseUnit        string         `json:"dispense_unit"`
	PieceContentAmount  pgtype.Numeric `json:"piece_content_amount"`
	PieceContentUnit    *string        `json:"piece_content_unit"`
	IsFractionalAllowed *bool          `json:"is_fractional_allowed"`
	DisplayAsPercentage *bool          `json:"display_as_percentage"`
	Barcode             *string        `json:"barcode"`
	Notes               *string        `json:"notes"`
	IsActive            bool           `json:"is_active"`
}

func (q *Queries) UpdateDrug(ctx context.Context, arg UpdateDrugParams) error {
	_, err := q.db.Exec(ctx, updateDrug,
		arg.ID,
		arg.GenericName,
		arg.BrandName,
		arg.DrugCode,
		arg.DosageFormCode,
		arg.RouteCode,
		arg.StrengthNum,
		arg.StrengthUnitNum,
		arg.StrengthDen,
		arg.StrengthUnitDen,
		arg.DispenseUnit,
		arg.PieceContentAmount,
		arg.PieceContentUnit,
		arg.IsFractionalAllowed,
		arg.DisplayAsPercentage,
		arg.Barcode,
		arg.Notes,
		arg.IsActive,
	)
	return err
}
