// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: prescriptions.sql

package db

import (
	"context"
	"time"
)

const countLinesForPrescription = `-- name: CountLinesForPrescription :one
SELECT COUNT(*) FROM prescription_lines WHERE prescription_id=$1
`

func (q *Queries) CountLinesForPrescription(ctx context.Context, prescriptionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLinesForPrescription, prescriptionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPackedLinesForPrescription = `-- name: CountPackedLinesForPrescription :one
SELECT COUNT(*) FROM prescription_lines WHERE prescription_id=$1 AND is_packed=TRUE
`

func (q *Queries) CountPackedLinesForPrescription(ctx context.Context, prescriptionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPackedLinesForPrescription, prescriptionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllocationsByLine = `-- name: DeleteAllocationsByLine :exec
DELETE FROM prescription_batch_items WHERE line_id=$1
`

func (q *Queries) DeleteAllocationsByLine(ctx context.Context, lineID int64) error {
	_, err := q.db.Exec(ctx, deleteAllocationsByLine, lineID)
	return err
}

const deleteAllocationsByPrescription = `-- name: DeleteAllocationsByPrescription :exec
DELETE FROM prescription_batch_items
WHERE line_id IN (SELECT id FROM prescription_lines WHERE prescription_id=$1)
`

func (q *Queries) DeleteAllocationsByPrescription(ctx context.Context, prescriptionID int64) error {
	_, err := q.db.Exec(ctx, deleteAllocationsByPrescription, prescriptionID)
	return err
}

const deleteLine = `-- name: DeleteLine :exec
DELETE FROM prescription_lines WHERE id=$1
`

func (q *Queries) DeleteLine(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLine, id)
	return err
}

const deleteLinesByPrescription = `-- name: DeleteLinesByPrescription :exec
DELETE FROM prescription_lines WHERE prescription_id=$1
`

func (q *Queries) DeleteLinesByPrescription(ctx context.Context, prescriptionID int64) error {
	_, err := q.db.Exec(ctx, deleteLinesByPrescription, prescriptionID)
	return err
}

const deletePrescription = `-- name: DeletePrescription :exec
DELETE FROM prescriptions WHERE id=$1
`

func (q *Queries) DeletePrescription(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePrescription, id)
	return err
}

const dispensePrescription = `-- name: DispensePrescription :exec
UPDATE prescriptions
SET is_dispensed=TRUE,
    dispensed_by = current_setting('sothea.user_id')::bigint,
    dispensed_at=NOW(),
    updated_at=NOW()
WHERE id=$1
`

func (q *Queries) DispensePrescription(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, dispensePrescription, id)
	return err
}

const getLineGuardForUpdate = `-- name: GetLineGuardForUpdate :one
SELECT drug_id,
       dose_amount, dose_unit,
       frequency_code,
       duration, duration_unit,
       remarks, prn
FROM prescription_lines
WHERE id=$1
FOR UPDATE
`

type GetLineGuardForUpdateRow struct {
	DrugID        int64   `json:"drug_id"`
	DoseAmount    float64 `json:"dose_amount"`
	DoseUnit      string  `json:"dose_unit"`
	FrequencyCode string  `json:"frequency_code"`
	Duration      float64 `json:"duration"`
	DurationUnit  string  `json:"duration_unit"`
	Remarks       *string `json:"remarks"`
	Prn           bool    `json:"prn"`
}

func (q *Queries) GetLineGuardForUpdate(ctx context.Context, id int64) (GetLineGuardForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getLineGuardForUpdate, id)
	var i GetLineGuardForUpdateRow
	err := row.Scan(
		&i.DrugID,
		&i.DoseAmount,
		&i.DoseUnit,
		&i.FrequencyCode,
		&i.Duration,
		&i.DurationUnit,
		&i.Remarks,
		&i.Prn,
	)
	return i, err
}

const getLineWithDispenseUnit = `-- name: GetLineWithDispenseUnit :one
SELECT
  pl.id, pl.prescription_id, pl.drug_id, pl.remarks, pl.prn,
  pl.dose_amount, pl.dose_unit,
  pl.frequency_code,
  pl.duration, pl.duration_unit,
  pl.total_to_dispense, pl.is_packed, pl.packed_by, pl.packed_at,
  (SELECT dispense_unit FROM drugs WHERE id=pl.drug_id) AS du
FROM prescription_lines pl
WHERE pl.id=$1
`

type GetLineWithDispenseUnitRow struct {
	ID              int64      `json:"id"`
	PrescriptionID  int64      `json:"prescription_id"`
	DrugID          int64      `json:"drug_id"`
	Remarks         *string    `json:"remarks"`
	Prn             bool       `json:"prn"`
	DoseAmount      float64    `json:"dose_amount"`
	DoseUnit        string     `json:"dose_unit"`
	FrequencyCode   string     `json:"frequency_code"`
	Duration        float64    `json:"duration"`
	DurationUnit    string     `json:"duration_unit"`
	TotalToDispense int32      `json:"total_to_dispense"`
	IsPacked        bool       `json:"is_packed"`
	PackedBy        *int64     `json:"packed_by"`
	PackedAt        *time.Time `json:"packed_at"`
	Du              string     `json:"du"`
}

func (q *Queries) GetLineWithDispenseUnit(ctx context.Context, id int64) (GetLineWithDispenseUnitRow, error) {
	row := q.db.QueryRow(ctx, getLineWithDispenseUnit, id)
	var i GetLineWithDispenseUnitRow
	err := row.Scan(
		&i.ID,
		&i.PrescriptionID,
		&i.DrugID,
		&i.Remarks,
		&i.Prn,
		&i.DoseAmount,
		&i.DoseUnit,
		&i.FrequencyCode,
		&i.Duration,
		&i.DurationUnit,
		&i.TotalToDispense,
		&i.IsPacked,
		&i.PackedBy,
		&i.PackedAt,
		&i.Du,
	)
	return i, err
}

const getPrescriptionDispensed = `-- name: GetPrescriptionDispensed :one
SELECT is_dispensed FROM prescriptions WHERE id=$1
`

func (q *Queries) GetPrescriptionDispensed(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, getPrescriptionDispensed, id)
	var is_dispensed bool
	err := row.Scan(&is_dispensed)
	return is_dispensed, err
}

const getPrescriptionHeader = `-- name: GetPrescriptionHeader :one
SELECT p.id, p.patient_id, p.vid, p.notes,
       p.created_by, p.created_at, p.updated_at,
       p.is_dispensed, p.dispensed_by, p.dispensed_at,
       uc.name AS creator_name,
       ud.name AS dispenser_name
FROM prescriptions p
LEFT JOIN users uc ON uc.id = p.created_by
LEFT JOIN users ud ON ud.id = p.dispensed_by
WHERE p.id = $1
`

type GetPrescriptionHeaderRow struct {
	ID            int64      `json:"id"`
	PatientID     int32      `json:"patient_id"`
	Vid           int32      `json:"vid"`
	Notes         *string    `json:"notes"`
	CreatedBy     *int64     `json:"created_by"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     *time.Time `json:"updated_at"`
	IsDispensed   bool       `json:"is_dispensed"`
	DispensedBy   *int64     `json:"dispensed_by"`
	DispensedAt   *time.Time `json:"dispensed_at"`
	CreatorName   *string    `json:"creator_name"`
	DispenserName *string    `json:"dispenser_name"`
}

func (q *Queries) GetPrescriptionHeader(ctx context.Context, id int64) (GetPrescriptionHeaderRow, error) {
	row := q.db.QueryRow(ctx, getPrescriptionHeader, id)
	var i GetPrescriptionHeaderRow
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.Vid,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDispensed,
		&i.DispensedBy,
		&i.DispensedAt,
		&i.CreatorName,
		&i.DispenserName,
	)
	return i, err
}

const getPrescriptionIDForLine = `-- name: GetPrescriptionIDForLine :one
SELECT prescription_id FROM prescription_lines WHERE id=$1
`

func (q *Queries) GetPrescriptionIDForLine(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getPrescriptionIDForLine, id)
	var prescription_id int64
	err := row.Scan(&prescription_id)
	return prescription_id, err
}

const insertAllocation = `-- name: InsertAllocation :one
INSERT INTO prescription_batch_items (line_id, batch_location_id, quantity)
VALUES ($1,$2,$3)
RETURNING id, created_at, updated_at
`

type InsertAllocationParams struct {
	LineID          int64 `json:"line_id"`
	BatchLocationID int64 `json:"batch_location_id"`
	Quantity        int32 `json:"quantity"`
}

type InsertAllocationRow struct {
	ID        int64      `json:"id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

func (q *Queries) InsertAllocation(ctx context.Context, arg InsertAllocationParams) (InsertAllocationRow, error) {
	row := q.db.QueryRow(ctx, insertAllocation, arg.LineID, arg.BatchLocationID, arg.Quantity)
	var i InsertAllocationRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const insertLine = `-- name: InsertLine :one

INSERT INTO prescription_lines (
  prescription_id, drug_id, remarks, prn,
  dose_amount, dose_unit,
  frequency_code,
  duration, duration_unit
) VALUES (
  $1,$2,$3,$4,
  $5,$6,
  $7,
  $8,$9
) RETURNING id, total_to_dispense, is_packed
`

type InsertLineParams struct {
	PrescriptionID int64   `json:"prescription_id"`
	DrugID         int64   `json:"drug_id"`
	Remarks        *string `json:"remarks"`
	Prn            bool    `json:"prn"`
	DoseAmount     float64 `json:"dose_amount"`
	DoseUnit       string  `json:"dose_unit"`
	FrequencyCode  string  `json:"frequency_code"`
	Duration       float64 `json:"duration"`
	DurationUnit   string  `json:"duration_unit"`
}

type InsertLineRow struct {
	ID              int64 `json:"id"`
	TotalToDispense int32 `json:"total_to_dispense"`
	IsPacked        bool  `json:"is_packed"`
}

// Lines ----------------------------------------------------------------------
func (q *Queries) InsertLine(ctx context.Context, arg InsertLineParams) (InsertLineRow, error) {
	row := q.db.QueryRow(ctx, insertLine,
		arg.PrescriptionID,
		arg.DrugID,
		arg.Remarks,
		arg.Prn,
		arg.DoseAmount,
		arg.DoseUnit,
		arg.FrequencyCode,
		arg.Duration,
		arg.DurationUnit,
	)
	var i InsertLineRow
	err := row.Scan(&i.ID, &i.TotalToDispense, &i.IsPacked)
	return i, err
}

const insertPrescription = `-- name: InsertPrescription :one

INSERT INTO prescriptions (patient_id, vid, notes)
VALUES ($1,$2,$3)
RETURNING id, created_at, updated_at
`

type InsertPrescriptionParams struct {
	PatientID int32   `json:"patient_id"`
	Vid       int32   `json:"vid"`
	Notes     *string `json:"notes"`
}

type InsertPrescriptionRow struct {
	ID        int64      `json:"id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

// Prescriptions --------------------------------------------------------------
func (q *Queries) InsertPrescription(ctx context.Context, arg InsertPrescriptionParams) (InsertPrescriptionRow, error) {
	row := q.db.QueryRow(ctx, insertPrescription, arg.PatientID, arg.Vid, arg.Notes)
	var i InsertPrescriptionRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listAllocationsByLine = `-- name: ListAllocationsByLine :many
SELECT id, line_id, batch_location_id, quantity, created_at, updated_at
FROM prescription_batch_items
WHERE line_id=$1
ORDER BY id
`

type ListAllocationsByLineRow struct {
	ID              int64      `json:"id"`
	LineID          int64      `json:"line_id"`
	BatchLocationID int64      `json:"batch_location_id"`
	Quantity        int32      `json:"quantity"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       *time.Time `json:"updated_at"`
}

func (q *Queries) ListAllocationsByLine(ctx context.Context, lineID int64) ([]ListAllocationsByLineRow, error) {
	rows, err := q.db.Query(ctx, listAllocationsByLine, lineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllocationsByLineRow
	for rows.Next() {
		var i ListAllocationsByLineRow
		if err := rows.Scan(
			&i.ID,
			&i.LineID,
			&i.BatchLocationID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllocationsByLineIDs = `-- name: ListAllocationsByLineIDs :many
SELECT id, line_id, batch_location_id, quantity, created_at, updated_at
FROM prescription_batch_items
WHERE line_id = ANY($1::bigint[])
ORDER BY line_id, id
`

type ListAllocationsByLineIDsRow struct {
	ID              int64      `json:"id"`
	LineID          int64      `json:"line_id"`
	BatchLocationID int64      `json:"batch_location_id"`
	Quantity        int32      `json:"quantity"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       *time.Time `json:"updated_at"`
}

func (q *Queries) ListAllocationsByLineIDs(ctx context.Context, dollar_1 []int64) ([]ListAllocationsByLineIDsRow, error) {
	rows, err := q.db.Query(ctx, listAllocationsByLineIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllocationsByLineIDsRow
	for rows.Next() {
		var i ListAllocationsByLineIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.LineID,
			&i.BatchLocationID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionLines = `-- name: ListPrescriptionLines :many
SELECT
  pl.id, pl.prescription_id, pl.drug_id, pl.remarks, pl.prn,
  pl.dose_amount, pl.dose_unit,
  pl.frequency_code,
  pl.duration, pl.duration_unit,
  pl.total_to_dispense, pl.is_packed, pl.packed_by, pl.packed_at,
  u1.name AS packer_name,
  u2.name AS updater_name,
  d.generic_name AS drug_name,
  d.route_code AS route_code,
  d.dispense_unit AS dispense_unit,
  CASE
    WHEN d.strength_num IS NULL AND d.strength_unit_num IS NULL THEN d.dosage_form_code
    WHEN d.strength_den IS NULL THEN d.strength_num::text || ' ' || d.strength_unit_num || '/' || d.dispense_unit
    ELSE d.strength_num::text || ' ' || d.strength_unit_num || '/' ||
         d.strength_den::text || ' ' || d.strength_unit_den
  END AS display_strength
FROM prescription_lines pl
LEFT JOIN drugs d ON d.id = pl.drug_id
LEFT JOIN users u1 ON u1.id = pl.packed_by
LEFT JOIN users u2 ON u2.id = pl.updated_by
WHERE pl.prescription_id = $1
ORDER BY pl.id
`

type ListPrescriptionLinesRow struct {
	ID              int64       `json:"id"`
	PrescriptionID  int64       `json:"prescription_id"`
	DrugID          int64       `json:"drug_id"`
	Remarks         *string     `json:"remarks"`
	Prn             bool        `json:"prn"`
	DoseAmount      float64     `json:"dose_amount"`
	DoseUnit        string      `json:"dose_unit"`
	FrequencyCode   string      `json:"frequency_code"`
	Duration        float64     `json:"duration"`
	DurationUnit    string      `json:"duration_unit"`
	TotalToDispense int32       `json:"total_to_dispense"`
	IsPacked        bool        `json:"is_packed"`
	PackedBy        *int64      `json:"packed_by"`
	PackedAt        *time.Time  `json:"packed_at"`
	PackerName      *string     `json:"packer_name"`
	UpdaterName     *string     `json:"updater_name"`
	DrugName        *string     `json:"drug_name"`
	RouteCode       *string     `json:"route_code"`
	DispenseUnit    *string     `json:"dispense_unit"`
	DisplayStrength interface{} `json:"display_strength"`
}

func (q *Queries) ListPrescriptionLines(ctx context.Context, prescriptionID int64) ([]ListPrescriptionLinesRow, error) {
	rows, err := q.db.Query(ctx, listPrescriptionLines, prescriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrescriptionLinesRow
	for rows.Next() {
		var i ListPrescriptionLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.PrescriptionID,
			&i.DrugID,
			&i.Remarks,
			&i.Prn,
			&i.DoseAmount,
			&i.DoseUnit,
			&i.FrequencyCode,
			&i.Duration,
			&i.DurationUnit,
			&i.TotalToDispense,
			&i.IsPacked,
			&i.PackedBy,
			&i.PackedAt,
			&i.PackerName,
			&i.UpdaterName,
			&i.DrugName,
			&i.RouteCode,
			&i.DispenseUnit,
			&i.DisplayStrength,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsAll = `-- name: ListPrescriptionsAll :many
SELECT id, patient_id, vid, notes,
       created_by, created_at, updated_at,
       is_dispensed, dispensed_by, dispensed_at
FROM prescriptions
ORDER BY created_at DESC
`

type ListPrescriptionsAllRow struct {
	ID          int64      `json:"id"`
	PatientID   int32      `json:"patient_id"`
	Vid         int32      `json:"vid"`
	Notes       *string    `json:"notes"`
	CreatedBy   *int64     `json:"created_by"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   *time.Time `json:"updated_at"`
	IsDispensed bool       `json:"is_dispensed"`
	DispensedBy *int64     `json:"dispensed_by"`
	DispensedAt *time.Time `json:"dispensed_at"`
}

func (q *Queries) ListPrescriptionsAll(ctx context.Context) ([]ListPrescriptionsAllRow, error) {
	rows, err := q.db.Query(ctx, listPrescriptionsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrescriptionsAllRow
	for rows.Next() {
		var i ListPrescriptionsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.Vid,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDispensed,
			&i.DispensedBy,
			&i.DispensedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsByPatient = `-- name: ListPrescriptionsByPatient :many
SELECT id, patient_id, vid, notes,
       created_by, created_at, updated_at,
       is_dispensed, dispensed_by, dispensed_at
FROM prescriptions
WHERE patient_id = $1
ORDER BY created_at DESC
`

type ListPrescriptionsByPatientRow struct {
	ID          int64      `json:"id"`
	PatientID   int32      `json:"patient_id"`
	Vid         int32      `json:"vid"`
	Notes       *string    `json:"notes"`
	CreatedBy   *int64     `json:"created_by"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   *time.Time `json:"updated_at"`
	IsDispensed bool       `json:"is_dispensed"`
	DispensedBy *int64     `json:"dispensed_by"`
	DispensedAt *time.Time `json:"dispensed_at"`
}

func (q *Queries) ListPrescriptionsByPatient(ctx context.Context, patientID int32) ([]ListPrescriptionsByPatientRow, error) {
	rows, err := q.db.Query(ctx, listPrescriptionsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrescriptionsByPatientRow
	for rows.Next() {
		var i ListPrescriptionsByPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.Vid,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDispensed,
			&i.DispensedBy,
			&i.DispensedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsByPatientVisit = `-- name: ListPrescriptionsByPatientVisit :many
SELECT id, patient_id, vid, notes,
       created_by, created_at, updated_at,
       is_dispensed, dispensed_by, dispensed_at
FROM prescriptions
WHERE patient_id = $1 AND vid = $2
ORDER BY created_at DESC
`

type ListPrescriptionsByPatientVisitParams struct {
	PatientID int32 `json:"patient_id"`
	Vid       int32 `json:"vid"`
}

type ListPrescriptionsByPatientVisitRow struct {
	ID          int64      `json:"id"`
	PatientID   int32      `json:"patient_id"`
	Vid         int32      `json:"vid"`
	Notes       *string    `json:"notes"`
	CreatedBy   *int64     `json:"created_by"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   *time.Time `json:"updated_at"`
	IsDispensed bool       `json:"is_dispensed"`
	DispensedBy *int64     `json:"dispensed_by"`
	DispensedAt *time.Time `json:"dispensed_at"`
}

func (q *Queries) ListPrescriptionsByPatientVisit(ctx context.Context, arg ListPrescriptionsByPatientVisitParams) ([]ListPrescriptionsByPatientVisitRow, error) {
	rows, err := q.db.Query(ctx, listPrescriptionsByPatientVisit, arg.PatientID, arg.Vid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrescriptionsByPatientVisitRow
	for rows.Next() {
		var i ListPrescriptionsByPatientVisitRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.Vid,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDispensed,
			&i.DispensedBy,
			&i.DispensedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLinePacked = `-- name: MarkLinePacked :exec
UPDATE prescription_lines
SET is_packed=TRUE,
    packed_by = current_setting('sothea.user_id')::bigint,
    packed_at=NOW()
WHERE id=$1
`

func (q *Queries) MarkLinePacked(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markLinePacked, id)
	return err
}

const unpackLine = `-- name: UnpackLine :exec
UPDATE prescription_lines
SET is_packed=FALSE, packed_by=NULL, packed_at=NULL, updated_at=NOW()
WHERE id=$1
`

func (q *Queries) UnpackLine(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, unpackLine, id)
	return err
}

const updateLine = `-- name: UpdateLine :one
UPDATE prescription_lines SET
  drug_id=$2, remarks=$3, prn=$4,
  dose_amount=$5, dose_unit=$6,
  frequency_code=$7,
  duration=$8, duration_unit=$9,
  is_packed=FALSE, packed_by=NULL, packed_at=NULL,
  updated_at=NOW()
WHERE id=$1
RETURNING total_to_dispense
`

type UpdateLineParams struct {
	ID            int64   `json:"id"`
	DrugID        int64   `json:"drug_id"`
	Remarks       *string `json:"remarks"`
	Prn           bool    `json:"prn"`
	DoseAmount    float64 `json:"dose_amount"`
	DoseUnit      string  `json:"dose_unit"`
	FrequencyCode string  `json:"frequency_code"`
	Duration      float64 `json:"duration"`
	DurationUnit  string  `json:"duration_unit"`
}

func (q *Queries) UpdateLine(ctx context.Context, arg UpdateLineParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateLine,
		arg.ID,
		arg.DrugID,
		arg.Remarks,
		arg.Prn,
		arg.DoseAmount,
		arg.DoseUnit,
		arg.FrequencyCode,
		arg.Duration,
		arg.DurationUnit,
	)
	var total_to_dispense int32
	err := row.Scan(&total_to_dispense)
	return total_to_dispense, err
}

const updatePrescriptionFull = `-- name: UpdatePrescriptionFull :exec
UPDATE prescriptions
SET patient_id=$2, vid=$3, notes=$4, updated_at=now()
WHERE id=$1
`

type UpdatePrescriptionFullParams struct {
	ID        int64   `json:"id"`
	PatientID int32   `json:"patient_id"`
	Vid       int32   `json:"vid"`
	Notes     *string `json:"notes"`
}

func (q *Queries) UpdatePrescriptionFull(ctx context.Context, arg UpdatePrescriptionFullParams) error {
	_, err := q.db.Exec(ctx, updatePrescriptionFull,
		arg.ID,
		arg.PatientID,
		arg.Vid,
		arg.Notes,
	)
	return err
}

const updatePrescriptionNotes = `-- name: UpdatePrescriptionNotes :exec
UPDATE prescriptions
SET notes=$2, updated_at=now()
WHERE id=$1
`

type UpdatePrescriptionNotesParams struct {
	ID    int64   `json:"id"`
	Notes *string `json:"notes"`
}

func (q *Queries) UpdatePrescriptionNotes(ctx context.Context, arg UpdatePrescriptionNotesParams) error {
	_, err := q.db.Exec(ctx, updatePrescriptionNotes, arg.ID, arg.Notes)
	return err
}
