version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      - POSTGRES_USER=jieqiboh
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=patients
    ports:
      - '5432:5432'
    volumes:
      # Mount and run the init.sql file to load data
      - ./sql/1_patients.up.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: postgres-docker-db