// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/jieqiboh/sothea_backend/entities"
	mock "github.com/stretchr/testify/mock"
)

// PharmacyUseCase is an autogenerated mock type for the PharmacyUseCase type
type PharmacyUseCase struct {
	mock.Mock
}

// CreateBatch provides a mock function with given fields: ctx, b
func (_m *PharmacyUseCase) CreateBatch(ctx context.Context, b *entities.DrugBatch) (int64, error) {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.DrugBatch) (int64, error)); ok {
		return rf(ctx, b)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.DrugBatch) int64); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.DrugBatch) error); ok {
		r1 = rf(ctx, b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDrug provides a mock function with given fields: ctx, d
func (_m *PharmacyUseCase) CreateDrug(ctx context.Context, d *entities.Drug) (*entities.Drug, error) {
	ret := _m.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for CreateDrug")
	}

	var r0 *entities.Drug
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Drug) (*entities.Drug, error)); ok {
		return rf(ctx, d)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Drug) *entities.Drug); ok {
		r0 = rf(ctx, d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Drug)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Drug) error); ok {
		r1 = rf(ctx, d)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBatch provides a mock function with given fields: ctx, id
func (_m *PharmacyUseCase) DeleteBatch(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDrug provides a mock function with given fields: ctx, id
func (_m *PharmacyUseCase) DeleteDrug(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDrug")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDrug provides a mock function with given fields: ctx, id
func (_m *PharmacyUseCase) GetDrug(ctx context.Context, id int64) (*entities.DrugDetail, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDrug")
	}

	var r0 *entities.DrugDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entities.DrugDetail, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entities.DrugDetail); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.DrugDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBatches provides a mock function with given fields: ctx, drugID
func (_m *PharmacyUseCase) ListBatches(ctx context.Context, drugID *int64) ([]entities.DrugBatch, error) {
	ret := _m.Called(ctx, drugID)

	if len(ret) == 0 {
		panic("no return value specified for ListBatches")
	}

	var r0 []entities.DrugBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *int64) ([]entities.DrugBatch, error)); ok {
		return rf(ctx, drugID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *int64) []entities.DrugBatch); ok {
		r0 = rf(ctx, drugID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.DrugBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *int64) error); ok {
		r1 = rf(ctx, drugID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDrugs provides a mock function with given fields: ctx
func (_m *PharmacyUseCase) ListDrugs(ctx context.Context) ([]entities.Drug, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListDrugs")
	}

	var r0 []entities.Drug
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.Drug, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.Drug); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Drug)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBatch provides a mock function with given fields: ctx, b
func (_m *PharmacyUseCase) UpdateBatch(ctx context.Context, b *entities.DrugBatch) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.DrugBatch) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDrug provides a mock function with given fields: ctx, d
func (_m *PharmacyUseCase) UpdateDrug(ctx context.Context, d *entities.Drug) (*entities.Drug, error) {
	ret := _m.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDrug")
	}

	var r0 *entities.Drug
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Drug) (*entities.Drug, error)); ok {
		return rf(ctx, d)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Drug) *entities.Drug); ok {
		r0 = rf(ctx, d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Drug)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Drug) error); ok {
		r1 = rf(ctx, d)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPharmacyUseCase creates a new instance of PharmacyUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPharmacyUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PharmacyUseCase {
	mock := &PharmacyUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
