// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/jieqiboh/sothea_backend/entities"
	mock "github.com/stretchr/testify/mock"
)

// PrescriptionUseCase is an autogenerated mock type for the PrescriptionUseCase type
type PrescriptionUseCase struct {
	mock.Mock
}

// CreatePrescription provides a mock function with given fields: ctx, p
func (_m *PrescriptionUseCase) CreatePrescription(ctx context.Context, p *entities.Prescription) (*entities.Prescription, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreatePrescription")
	}

	var r0 *entities.Prescription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Prescription) (*entities.Prescription, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Prescription) *entities.Prescription); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Prescription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Prescription) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePrescription provides a mock function with given fields: ctx, id
func (_m *PrescriptionUseCase) DeletePrescription(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePrescription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPrescriptionByID provides a mock function with given fields: ctx, id
func (_m *PrescriptionUseCase) GetPrescriptionByID(ctx context.Context, id int64) (*entities.Prescription, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPrescriptionByID")
	}

	var r0 *entities.Prescription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entities.Prescription, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entities.Prescription); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Prescription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPrescriptions provides a mock function with given fields: ctx, patientID, vid
func (_m *PrescriptionUseCase) ListPrescriptions(ctx context.Context, patientID *int64, vid *int32) ([]*entities.Prescription, error) {
	ret := _m.Called(ctx, patientID, vid)

	if len(ret) == 0 {
		panic("no return value specified for ListPrescriptions")
	}

	var r0 []*entities.Prescription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *int64, *int32) ([]*entities.Prescription, error)); ok {
		return rf(ctx, patientID, vid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *int64, *int32) []*entities.Prescription); ok {
		r0 = rf(ctx, patientID, vid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Prescription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *int64, *int32) error); ok {
		r1 = rf(ctx, patientID, vid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePrescription provides a mock function with given fields: ctx, p
func (_m *PrescriptionUseCase) UpdatePrescription(ctx context.Context, p *entities.Prescription) (*entities.Prescription, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePrescription")
	}

	var r0 *entities.Prescription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Prescription) (*entities.Prescription, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Prescription) *entities.Prescription); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Prescription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Prescription) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPrescriptionUseCase creates a new instance of PrescriptionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrescriptionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrescriptionUseCase {
	mock := &PrescriptionUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
