// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/jieqiboh/sothea_backend/entities"
	mock "github.com/stretchr/testify/mock"
)

// PrescriptionUseCase is an autogenerated mock type for the PrescriptionUseCase type
type PrescriptionUseCase struct {
	mock.Mock
}

type PrescriptionUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *PrescriptionUseCase) EXPECT() *PrescriptionUseCase_Expecter {
	return &PrescriptionUseCase_Expecter{mock: &_m.Mock}
}

// AddLine provides a mock function with given fields: ctx, line
func (_m *PrescriptionUseCase) AddLine(ctx context.Context, line *entities.PrescriptionLine) (*entities.PrescriptionLine, error) {
	ret := _m.Called(ctx, line)

	if len(ret) == 0 {
		panic("no return value specified for AddLine")
	}

	var r0 *entities.PrescriptionLine
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.PrescriptionLine) (*entities.PrescriptionLine, error)); ok {
		return rf(ctx, line)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.PrescriptionLine) *entities.PrescriptionLine); ok {
		r0 = rf(ctx, line)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.PrescriptionLine)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.PrescriptionLine) error); ok {
		r1 = rf(ctx, line)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PrescriptionUseCase_AddLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddLine'
type PrescriptionUseCase_AddLine_Call struct {
	*mock.Call
}

// AddLine is a helper method to define mock.On call
//   - ctx context.Context
//   - line *entities.PrescriptionLine
func (_e *PrescriptionUseCase_Expecter) AddLine(ctx interface{}, line interface{}) *PrescriptionUseCase_AddLine_Call {
	return &PrescriptionUseCase_AddLine_Call{Call: _e.mock.On("AddLine", ctx, line)}
}

func (_c *PrescriptionUseCase_AddLine_Call) Run(run func(ctx context.Context, line *entities.PrescriptionLine)) *PrescriptionUseCase_AddLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.PrescriptionLine))
	})
	return _c
}

func (_c *PrescriptionUseCase_AddLine_Call) Return(_a0 *entities.PrescriptionLine, _a1 error) *PrescriptionUseCase_AddLine_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PrescriptionUseCase_AddLine_Call) RunAndReturn(run func(context.Context, *entities.PrescriptionLine) (*entities.PrescriptionLine, error)) *PrescriptionUseCase_AddLine_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePrescription provides a mock function with given fields: ctx, p
func (_m *PrescriptionUseCase) CreatePrescription(ctx context.Context, p *entities.Prescription) (*entities.Prescription, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreatePrescription")
	}

	var r0 *entities.Prescription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Prescription) (*entities.Prescription, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Prescription) *entities.Prescription); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Prescription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Prescription) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PrescriptionUseCase_CreatePrescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePrescription'
type PrescriptionUseCase_CreatePrescription_Call struct {
	*mock.Call
}

// CreatePrescription is a helper method to define mock.On call
//   - ctx context.Context
//   - p *entities.Prescription
func (_e *PrescriptionUseCase_Expecter) CreatePrescription(ctx interface{}, p interface{}) *PrescriptionUseCase_CreatePrescription_Call {
	return &PrescriptionUseCase_CreatePrescription_Call{Call: _e.mock.On("CreatePrescription", ctx, p)}
}

func (_c *PrescriptionUseCase_CreatePrescription_Call) Run(run func(ctx context.Context, p *entities.Prescription)) *PrescriptionUseCase_CreatePrescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Prescription))
	})
	return _c
}

func (_c *PrescriptionUseCase_CreatePrescription_Call) Return(_a0 *entities.Prescription, _a1 error) *PrescriptionUseCase_CreatePrescription_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PrescriptionUseCase_CreatePrescription_Call) RunAndReturn(run func(context.Context, *entities.Prescription) (*entities.Prescription, error)) *PrescriptionUseCase_CreatePrescription_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePrescription provides a mock function with given fields: ctx, id
func (_m *PrescriptionUseCase) DeletePrescription(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePrescription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PrescriptionUseCase_DeletePrescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePrescription'
type PrescriptionUseCase_DeletePrescription_Call struct {
	*mock.Call
}

// DeletePrescription is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *PrescriptionUseCase_Expecter) DeletePrescription(ctx interface{}, id interface{}) *PrescriptionUseCase_DeletePrescription_Call {
	return &PrescriptionUseCase_DeletePrescription_Call{Call: _e.mock.On("DeletePrescription", ctx, id)}
}

func (_c *PrescriptionUseCase_DeletePrescription_Call) Run(run func(ctx context.Context, id int64)) *PrescriptionUseCase_DeletePrescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PrescriptionUseCase_DeletePrescription_Call) Return(_a0 error) *PrescriptionUseCase_DeletePrescription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PrescriptionUseCase_DeletePrescription_Call) RunAndReturn(run func(context.Context, int64) error) *PrescriptionUseCase_DeletePrescription_Call {
	_c.Call.Return(run)
	return _c
}

// DispensePrescription provides a mock function with given fields: ctx, prescriptionID
func (_m *PrescriptionUseCase) DispensePrescription(ctx context.Context, prescriptionID int64) (*entities.Prescription, error) {
	ret := _m.Called(ctx, prescriptionID)

	if len(ret) == 0 {
		panic("no return value specified for DispensePrescription")
	}

	var r0 *entities.Prescription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entities.Prescription, error)); ok {
		return rf(ctx, prescriptionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entities.Prescription); ok {
		r0 = rf(ctx, prescriptionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Prescription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, prescriptionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PrescriptionUseCase_DispensePrescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispensePrescription'
type PrescriptionUseCase_DispensePrescription_Call struct {
	*mock.Call
}

// DispensePrescription is a helper method to define mock.On call
//   - ctx context.Context
//   - prescriptionID int64
func (_e *PrescriptionUseCase_Expecter) DispensePrescription(ctx interface{}, prescriptionID interface{}) *PrescriptionUseCase_DispensePrescription_Call {
	return &PrescriptionUseCase_DispensePrescription_Call{Call: _e.mock.On("DispensePrescription", ctx, prescriptionID)}
}

func (_c *PrescriptionUseCase_DispensePrescription_Call) Run(run func(ctx context.Context, prescriptionID int64)) *PrescriptionUseCase_DispensePrescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PrescriptionUseCase_DispensePrescription_Call) Return(_a0 *entities.Prescription, _a1 error) *PrescriptionUseCase_DispensePrescription_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PrescriptionUseCase_DispensePrescription_Call) RunAndReturn(run func(context.Context, int64) (*entities.Prescription, error)) *PrescriptionUseCase_DispensePrescription_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrescriptionByID provides a mock function with given fields: ctx, id
func (_m *PrescriptionUseCase) GetPrescriptionByID(ctx context.Context, id int64) (*entities.Prescription, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPrescriptionByID")
	}

	var r0 *entities.Prescription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entities.Prescription, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entities.Prescription); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Prescription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PrescriptionUseCase_GetPrescriptionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrescriptionByID'
type PrescriptionUseCase_GetPrescriptionByID_Call struct {
	*mock.Call
}

// GetPrescriptionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *PrescriptionUseCase_Expecter) GetPrescriptionByID(ctx interface{}, id interface{}) *PrescriptionUseCase_GetPrescriptionByID_Call {
	return &PrescriptionUseCase_GetPrescriptionByID_Call{Call: _e.mock.On("GetPrescriptionByID", ctx, id)}
}

func (_c *PrescriptionUseCase_GetPrescriptionByID_Call) Run(run func(ctx context.Context, id int64)) *PrescriptionUseCase_GetPrescriptionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PrescriptionUseCase_GetPrescriptionByID_Call) Return(_a0 *entities.Prescription, _a1 error) *PrescriptionUseCase_GetPrescriptionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PrescriptionUseCase_GetPrescriptionByID_Call) RunAndReturn(run func(context.Context, int64) (*entities.Prescription, error)) *PrescriptionUseCase_GetPrescriptionByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListLineAllocations provides a mock function with given fields: ctx, lineID
func (_m *PrescriptionUseCase) ListLineAllocations(ctx context.Context, lineID int64) ([]entities.LineAllocation, error) {
	ret := _m.Called(ctx, lineID)

	if len(ret) == 0 {
		panic("no return value specified for ListLineAllocations")
	}

	var r0 []entities.LineAllocation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]entities.LineAllocation, error)); ok {
		return rf(ctx, lineID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []entities.LineAllocation); ok {
		r0 = rf(ctx, lineID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.LineAllocation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, lineID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PrescriptionUseCase_ListLineAllocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLineAllocations'
type PrescriptionUseCase_ListLineAllocations_Call struct {
	*mock.Call
}

// ListLineAllocations is a helper method to define mock.On call
//   - ctx context.Context
//   - lineID int64
func (_e *PrescriptionUseCase_Expecter) ListLineAllocations(ctx interface{}, lineID interface{}) *PrescriptionUseCase_ListLineAllocations_Call {
	return &PrescriptionUseCase_ListLineAllocations_Call{Call: _e.mock.On("ListLineAllocations", ctx, lineID)}
}

func (_c *PrescriptionUseCase_ListLineAllocations_Call) Run(run func(ctx context.Context, lineID int64)) *PrescriptionUseCase_ListLineAllocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PrescriptionUseCase_ListLineAllocations_Call) Return(_a0 []entities.LineAllocation, _a1 error) *PrescriptionUseCase_ListLineAllocations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PrescriptionUseCase_ListLineAllocations_Call) RunAndReturn(run func(context.Context, int64) ([]entities.LineAllocation, error)) *PrescriptionUseCase_ListLineAllocations_Call {
	_c.Call.Return(run)
	return _c
}

// ListPrescriptions provides a mock function with given fields: ctx, patientID, vid
func (_m *PrescriptionUseCase) ListPrescriptions(ctx context.Context, patientID *int64, vid *int32) ([]*entities.Prescription, error) {
	ret := _m.Called(ctx, patientID, vid)

	if len(ret) == 0 {
		panic("no return value specified for ListPrescriptions")
	}

	var r0 []*entities.Prescription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *int64, *int32) ([]*entities.Prescription, error)); ok {
		return rf(ctx, patientID, vid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *int64, *int32) []*entities.Prescription); ok {
		r0 = rf(ctx, patientID, vid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Prescription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *int64, *int32) error); ok {
		r1 = rf(ctx, patientID, vid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PrescriptionUseCase_ListPrescriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPrescriptions'
type PrescriptionUseCase_ListPrescriptions_Call struct {
	*mock.Call
}

// ListPrescriptions is a helper method to define mock.On call
//   - ctx context.Context
//   - patientID *int64
//   - vid *int32
func (_e *PrescriptionUseCase_Expecter) ListPrescriptions(ctx interface{}, patientID interface{}, vid interface{}) *PrescriptionUseCase_ListPrescriptions_Call {
	return &PrescriptionUseCase_ListPrescriptions_Call{Call: _e.mock.On("ListPrescriptions", ctx, patientID, vid)}
}

func (_c *PrescriptionUseCase_ListPrescriptions_Call) Run(run func(ctx context.Context, patientID *int64, vid *int32)) *PrescriptionUseCase_ListPrescriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*int64), args[2].(*int32))
	})
	return _c
}

func (_c *PrescriptionUseCase_ListPrescriptions_Call) Return(_a0 []*entities.Prescription, _a1 error) *PrescriptionUseCase_ListPrescriptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PrescriptionUseCase_ListPrescriptions_Call) RunAndReturn(run func(context.Context, *int64, *int32) ([]*entities.Prescription, error)) *PrescriptionUseCase_ListPrescriptions_Call {
	_c.Call.Return(run)
	return _c
}

// MarkLinePacked provides a mock function with given fields: ctx, lineID
func (_m *PrescriptionUseCase) MarkLinePacked(ctx context.Context, lineID int64) (*entities.PrescriptionLine, error) {
	ret := _m.Called(ctx, lineID)

	if len(ret) == 0 {
		panic("no return value specified for MarkLinePacked")
	}

	var r0 *entities.PrescriptionLine
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entities.PrescriptionLine, error)); ok {
		return rf(ctx, lineID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entities.PrescriptionLine); ok {
		r0 = rf(ctx, lineID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.PrescriptionLine)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, lineID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PrescriptionUseCase_MarkLinePacked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkLinePacked'
type PrescriptionUseCase_MarkLinePacked_Call struct {
	*mock.Call
}

// MarkLinePacked is a helper method to define mock.On call
//   - ctx context.Context
//   - lineID int64
func (_e *PrescriptionUseCase_Expecter) MarkLinePacked(ctx interface{}, lineID interface{}) *PrescriptionUseCase_MarkLinePacked_Call {
	return &PrescriptionUseCase_MarkLinePacked_Call{Call: _e.mock.On("MarkLinePacked", ctx, lineID)}
}

func (_c *PrescriptionUseCase_MarkLinePacked_Call) Run(run func(ctx context.Context, lineID int64)) *PrescriptionUseCase_MarkLinePacked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PrescriptionUseCase_MarkLinePacked_Call) Return(_a0 *entities.PrescriptionLine, _a1 error) *PrescriptionUseCase_MarkLinePacked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PrescriptionUseCase_MarkLinePacked_Call) RunAndReturn(run func(context.Context, int64) (*entities.PrescriptionLine, error)) *PrescriptionUseCase_MarkLinePacked_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveLine provides a mock function with given fields: ctx, lineID
func (_m *PrescriptionUseCase) RemoveLine(ctx context.Context, lineID int64) error {
	ret := _m.Called(ctx, lineID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveLine")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, lineID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PrescriptionUseCase_RemoveLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveLine'
type PrescriptionUseCase_RemoveLine_Call struct {
	*mock.Call
}

// RemoveLine is a helper method to define mock.On call
//   - ctx context.Context
//   - lineID int64
func (_e *PrescriptionUseCase_Expecter) RemoveLine(ctx interface{}, lineID interface{}) *PrescriptionUseCase_RemoveLine_Call {
	return &PrescriptionUseCase_RemoveLine_Call{Call: _e.mock.On("RemoveLine", ctx, lineID)}
}

func (_c *PrescriptionUseCase_RemoveLine_Call) Run(run func(ctx context.Context, lineID int64)) *PrescriptionUseCase_RemoveLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PrescriptionUseCase_RemoveLine_Call) Return(_a0 error) *PrescriptionUseCase_RemoveLine_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PrescriptionUseCase_RemoveLine_Call) RunAndReturn(run func(context.Context, int64) error) *PrescriptionUseCase_RemoveLine_Call {
	_c.Call.Return(run)
	return _c
}

// SetLineAllocations provides a mock function with given fields: ctx, lineID, allocs
func (_m *PrescriptionUseCase) SetLineAllocations(ctx context.Context, lineID int64, allocs []entities.LineAllocation) ([]entities.LineAllocation, error) {
	ret := _m.Called(ctx, lineID, allocs)

	if len(ret) == 0 {
		panic("no return value specified for SetLineAllocations")
	}

	var r0 []entities.LineAllocation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []entities.LineAllocation) ([]entities.LineAllocation, error)); ok {
		return rf(ctx, lineID, allocs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, []entities.LineAllocation) []entities.LineAllocation); ok {
		r0 = rf(ctx, lineID, allocs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.LineAllocation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, []entities.LineAllocation) error); ok {
		r1 = rf(ctx, lineID, allocs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PrescriptionUseCase_SetLineAllocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLineAllocations'
type PrescriptionUseCase_SetLineAllocations_Call struct {
	*mock.Call
}

// SetLineAllocations is a helper method to define mock.On call
//   - ctx context.Context
//   - lineID int64
//   - allocs []entities.LineAllocation
func (_e *PrescriptionUseCase_Expecter) SetLineAllocations(ctx interface{}, lineID interface{}, allocs interface{}) *PrescriptionUseCase_SetLineAllocations_Call {
	return &PrescriptionUseCase_SetLineAllocations_Call{Call: _e.mock.On("SetLineAllocations", ctx, lineID, allocs)}
}

func (_c *PrescriptionUseCase_SetLineAllocations_Call) Run(run func(ctx context.Context, lineID int64, allocs []entities.LineAllocation)) *PrescriptionUseCase_SetLineAllocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]entities.LineAllocation))
	})
	return _c
}

func (_c *PrescriptionUseCase_SetLineAllocations_Call) Return(_a0 []entities.LineAllocation, _a1 error) *PrescriptionUseCase_SetLineAllocations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PrescriptionUseCase_SetLineAllocations_Call) RunAndReturn(run func(context.Context, int64, []entities.LineAllocation) ([]entities.LineAllocation, error)) *PrescriptionUseCase_SetLineAllocations_Call {
	_c.Call.Return(run)
	return _c
}

// SuggestFEFOAllocations provides a mock function with given fields: ctx, lineID
func (_m *PrescriptionUseCase) SuggestFEFOAllocations(ctx context.Context, lineID int64) ([]entities.LineAllocation, error) {
	ret := _m.Called(ctx, lineID)

	if len(ret) == 0 {
		panic("no return value specified for SuggestFEFOAllocations")
	}

	var r0 []entities.LineAllocation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]entities.LineAllocation, error)); ok {
		return rf(ctx, lineID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []entities.LineAllocation); ok {
		r0 = rf(ctx, lineID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.LineAllocation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, lineID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PrescriptionUseCase_SuggestFEFOAllocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuggestFEFOAllocations'
type PrescriptionUseCase_SuggestFEFOAllocations_Call struct {
	*mock.Call
}

// SuggestFEFOAllocations is a helper method to define mock.On call
//   - ctx context.Context
//   - lineID int64
func (_e *PrescriptionUseCase_Expecter) SuggestFEFOAllocations(ctx interface{}, lineID interface{}) *PrescriptionUseCase_SuggestFEFOAllocations_Call {
	return &PrescriptionUseCase_SuggestFEFOAllocations_Call{Call: _e.mock.On("SuggestFEFOAllocations", ctx, lineID)}
}

func (_c *PrescriptionUseCase_SuggestFEFOAllocations_Call) Run(run func(ctx context.Context, lineID int64)) *PrescriptionUseCase_SuggestFEFOAllocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PrescriptionUseCase_SuggestFEFOAllocations_Call) Return(_a0 []entities.LineAllocation, _a1 error) *PrescriptionUseCase_SuggestFEFOAllocations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PrescriptionUseCase_SuggestFEFOAllocations_Call) RunAndReturn(run func(context.Context, int64) ([]entities.LineAllocation, error)) *PrescriptionUseCase_SuggestFEFOAllocations_Call {
	_c.Call.Return(run)
	return _c
}

// UnpackLine provides a mock function with given fields: ctx, lineID
func (_m *PrescriptionUseCase) UnpackLine(ctx context.Context, lineID int64) (*entities.PrescriptionLine, error) {
	ret := _m.Called(ctx, lineID)

	if len(ret) == 0 {
		panic("no return value specified for UnpackLine")
	}

	var r0 *entities.PrescriptionLine
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entities.PrescriptionLine, error)); ok {
		return rf(ctx, lineID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entities.PrescriptionLine); ok {
		r0 = rf(ctx, lineID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.PrescriptionLine)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, lineID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PrescriptionUseCase_UnpackLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnpackLine'
type PrescriptionUseCase_UnpackLine_Call struct {
	*mock.Call
}

// UnpackLine is a helper method to define mock.On call
//   - ctx context.Context
//   - lineID int64
func (_e *PrescriptionUseCase_Expecter) UnpackLine(ctx interface{}, lineID interface{}) *PrescriptionUseCase_UnpackLine_Call {
	return &PrescriptionUseCase_UnpackLine_Call{Call: _e.mock.On("UnpackLine", ctx, lineID)}
}

func (_c *PrescriptionUseCase_UnpackLine_Call) Run(run func(ctx context.Context, lineID int64)) *PrescriptionUseCase_UnpackLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PrescriptionUseCase_UnpackLine_Call) Return(_a0 *entities.PrescriptionLine, _a1 error) *PrescriptionUseCase_UnpackLine_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PrescriptionUseCase_UnpackLine_Call) RunAndReturn(run func(context.Context, int64) (*entities.PrescriptionLine, error)) *PrescriptionUseCase_UnpackLine_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLine provides a mock function with given fields: ctx, line
func (_m *PrescriptionUseCase) UpdateLine(ctx context.Context, line *entities.PrescriptionLine) (*entities.PrescriptionLine, error) {
	ret := _m.Called(ctx, line)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLine")
	}

	var r0 *entities.PrescriptionLine
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.PrescriptionLine) (*entities.PrescriptionLine, error)); ok {
		return rf(ctx, line)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.PrescriptionLine) *entities.PrescriptionLine); ok {
		r0 = rf(ctx, line)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.PrescriptionLine)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.PrescriptionLine) error); ok {
		r1 = rf(ctx, line)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PrescriptionUseCase_UpdateLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLine'
type PrescriptionUseCase_UpdateLine_Call struct {
	*mock.Call
}

// UpdateLine is a helper method to define mock.On call
//   - ctx context.Context
//   - line *entities.PrescriptionLine
func (_e *PrescriptionUseCase_Expecter) UpdateLine(ctx interface{}, line interface{}) *PrescriptionUseCase_UpdateLine_Call {
	return &PrescriptionUseCase_UpdateLine_Call{Call: _e.mock.On("UpdateLine", ctx, line)}
}

func (_c *PrescriptionUseCase_UpdateLine_Call) Run(run func(ctx context.Context, line *entities.PrescriptionLine)) *PrescriptionUseCase_UpdateLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.PrescriptionLine))
	})
	return _c
}

func (_c *PrescriptionUseCase_UpdateLine_Call) Return(_a0 *entities.PrescriptionLine, _a1 error) *PrescriptionUseCase_UpdateLine_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PrescriptionUseCase_UpdateLine_Call) RunAndReturn(run func(context.Context, *entities.PrescriptionLine) (*entities.PrescriptionLine, error)) *PrescriptionUseCase_UpdateLine_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePrescription provides a mock function with given fields: ctx, p
func (_m *PrescriptionUseCase) UpdatePrescription(ctx context.Context, p *entities.Prescription) (*entities.Prescription, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePrescription")
	}

	var r0 *entities.Prescription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Prescription) (*entities.Prescription, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Prescription) *entities.Prescription); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Prescription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Prescription) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PrescriptionUseCase_UpdatePrescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePrescription'
type PrescriptionUseCase_UpdatePrescription_Call struct {
	*mock.Call
}

// UpdatePrescription is a helper method to define mock.On call
//   - ctx context.Context
//   - p *entities.Prescription
func (_e *PrescriptionUseCase_Expecter) UpdatePrescription(ctx interface{}, p interface{}) *PrescriptionUseCase_UpdatePrescription_Call {
	return &PrescriptionUseCase_UpdatePrescription_Call{Call: _e.mock.On("UpdatePrescription", ctx, p)}
}

func (_c *PrescriptionUseCase_UpdatePrescription_Call) Run(run func(ctx context.Context, p *entities.Prescription)) *PrescriptionUseCase_UpdatePrescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Prescription))
	})
	return _c
}

func (_c *PrescriptionUseCase_UpdatePrescription_Call) Return(_a0 *entities.Prescription, _a1 error) *PrescriptionUseCase_UpdatePrescription_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PrescriptionUseCase_UpdatePrescription_Call) RunAndReturn(run func(context.Context, *entities.Prescription) (*entities.Prescription, error)) *PrescriptionUseCase_UpdatePrescription_Call {
	_c.Call.Return(run)
	return _c
}

// NewPrescriptionUseCase creates a new instance of PrescriptionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrescriptionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrescriptionUseCase {
	mock := &PrescriptionUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
